### ISSUE TITLE
Make saving the confusion matrix optional

### ISSUE THREAD

**Issue by schoersch** [marrlab/DomainLab#101]
I think it is not desirable, that the benchmark floods the storage with confusion matrix image files.
Additionally, this makes the benchmark setup more complicated.

**Comment by xinyuejohn** [comment]
> I think it is not desirable, that the benchmark floods the storage with confusion matrix image files. Additionally, this makes the benchmark setup more complicated.

Thanks Georg for your suggestion! Confusion matrix image files are saved in zouput and they are generated once for each model instead of each epoch. And I just checked the saved .png file is around 10 kB, which is acceptable I think. 

Could you explain to me why "this makes the benchmark setup more complicated."? I want to see if I can help with this

**Comment by smilesun** [comment]
@schoersch @xinyuejohn , in original version of DomainLab we have options to save models on disk after training, and also avoid diva generating images to disk, i guess we just need an option not to save confusion matrix with something liek python main_out.py --no-dump?

**Comment by schoersch** [comment]
> @schoersch @xinyuejohn , in original version of DomainLab we have options to save models on disk after training, and also avoid diva generating images to disk, i guess we just need an option not to save confusion matrix with something liek python main_out.py --no-dump?

That's what I wanted to suggest.
The thing is that we have a file then per task and parameter sample and these are not well comparable.

Snakemake likes it best if every created file is specified. But this is also not the case for the files created in saved_models, so this seems to be no problem, in contrast to my expectation.

**Comment by smilesun** [comment]
@xinyuejohn , do you want to create a small issue to resolve it by a pull request to master?
