### ISSUE TITLE
command line solution to execute tiny benchmark code on laptop

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#104]
We need a simple setting to test the plots of a tiny benchmark experiments where everyone can run on a laptop, @schoersch , could you update what I wrong here or give a pointer? 

```
git clone git@github.com:marrlab/DomainLab.git
git checkout benchmark-snakemake
snakemake --config=benchmark.yaml

```

**Comment by schoersch** [comment]
> We need a simple setting to test the plots of a tiny benchmark experiments where everyone can run on a laptop, @schoersch , could you update what I wrong here or give a pointer?
> 
> ```
> git clone git@github.com:marrlab/DomainLab.git
> git checkout benchmark-snakemake
> snakemake --config=benchmark.yaml
> ```

I'm sorry. Of course I have to point out to [run_snakemake.sh](https://github.com/marrlab/DomainLab/blob/6ab0da842ab43bd3facf44fe49a0f5293990cfc2/examples/benchmark/run_snakemake.sh). I used this file to run the snakemake from the DomainLab directory using `$ ./examples/benchmark/run_snakemake.sh`

**Comment by smilesun** [comment]
@rahulbshrestha @xinyuejohn  has it worked on your laptop?

**Comment by smilesun** [comment]
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                   count    min threads    max threads
------------------  -------  -------------  -------------
agg_results               1              1              1
all                       1              1              1
gen_plots                 1              1              1
parameter_sampling        1              1              1
run_experiment            3              1              1
total                     7              1              1

Select jobs to execute...

[Fri Feb 17 14:06:21 2023]
rule parameter_sampling:
    input: /home/sunxd/domainlab_master/examples/yaml/demo_benchmark.yaml
    output: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    jobid: 4
    reason: Missing output files: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    resources: tmpdir=/tmp

[Fri Feb 17 14:06:22 2023]
Finished job 4.
1 of 7 steps (14%) done
Select jobs to execute...

[Fri Feb 17 14:06:22 2023]
rule run_experiment:
    input: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    output: zoutput/benchmarks/demo_benchmark/rule_results/0.csv
    jobid: 3
    reason: Missing output files: zoutput/benchmarks/demo_benchmark/rule_results/0.csv; Input files updated by another job: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    wildcards: index=0
    resources: tmpdir=/tmp

[Fri Feb 17 14:10:10 2023]
Finished job 3.
2 of 7 steps (29%) done
Select jobs to execute...

[Fri Feb 17 14:10:10 2023]
rule run_experiment:
    input: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    output: zoutput/benchmarks/demo_benchmark/rule_results/1.csv
    jobid: 5
    reason: Missing output files: zoutput/benchmarks/demo_benchmark/rule_results/1.csv; Input files updated by another job: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    wildcards: index=1
    resources: tmpdir=/tmp

[Fri Feb 17 14:15:03 2023]
Finished job 5.
3 of 7 steps (43%) done
Select jobs to execute...

[Fri Feb 17 14:15:03 2023]
rule run_experiment:
    input: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    output: zoutput/benchmarks/demo_benchmark/rule_results/2.csv
    jobid: 6
    reason: Missing output files: zoutput/benchmarks/demo_benchmark/rule_results/2.csv; Input files updated by another job: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    wildcards: index=2
    resources: tmpdir=/tmp

[Fri Feb 17 14:16:48 2023]
Finished job 6.
4 of 7 steps (57%) done
Select jobs to execute...

[Fri Feb 17 14:16:48 2023]
rule agg_results:
    input: zoutput/benchmarks/demo_benchmark/rule_results/0.csv, zoutput/benchmarks/demo_benchmark/rule_results/1.csv, zoutput/benchmarks/demo_benchmark/rule_results/2.csv
    output: zoutput/benchmarks/demo_benchmark/results.csv
    jobid: 2
    reason: Missing output files: zoutput/benchmarks/demo_benchmark/results.csv; Input files updated by another job: zoutput/benchmarks/demo_benchmark/rule_results/1.csv, zoutput/benchmarks/demo_benchmark/rule_results/2.csv, zoutput/benchmarks/demo_benchmark/rule_results/0.csv
    resources: tmpdir=/tmp

[Fri Feb 17 14:16:49 2023]
Finished job 2.
5 of 7 steps (71%) done
Removing temporary output zoutput/benchmarks/demo_benchmark/rule_results/0.csv.
Removing temporary output zoutput/benchmarks/demo_benchmark/rule_results/1.csv.
Removing temporary output zoutput/benchmarks/demo_benchmark/rule_results/2.csv.
Select jobs to execute...

[Fri Feb 17 14:16:49 2023]
rule gen_plots:
    input: zoutput/benchmarks/demo_benchmark/results.csv
    output: zoutput/benchmarks/demo_benchmark/graphics
    jobid: 1
    reason: Missing output files: zoutput/benchmarks/demo_benchmark/graphics; Input files updated by another job: zoutput/benchmarks/demo_benchmark/results.csv
    resources: tmpdir=/tmp

Removing output files of failed job gen_plots since they might be corrupted:
zoutput/benchmarks/demo_benchmark/graphics
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-02-17T140621.251923.snakemake.log

**Comment by schoersch** [comment]
@smilesun this looks like everything works fine until it tries to plot. There should also be the `results.csv` file holding all results.

Could you try with the code from benchmark_snakemake2 ?

**Comment by smilesun** [comment]
@schoersch , after fixing the gpu memory issue, I met the same problem with the plot, I could get all the results, but the snakemake fails at the last step, i will check what went wrong on my side. 

```
WARNING: disabling kde because cov matrix is singular for objectives f1 & auroc
/home/sunxd/anaconda3/lib/python3.9/site-packages/seaborn/axisgrid.py:1690: UserWarning: Starting a Matpl
otlib GUI outside of the main thread will likely fail.
  f = plt.figure(figsize=(height, height))
Segmentation fault (core dumped)
Removing output files of failed job gen_plots since they might be corrupted:
zoutput/benchmarks/demo_benchmark/graphics
Exiting because a job execution failed. Look above for error messag
```

**Comment by smilesun** [comment]
what backend are you using? @Car-la-F 

https://matplotlib.org/stable/users/explain/backends.html

**Comment by smilesun** [comment]
after chaning the backend to "tkagg",
i met a new error:

ARNING: disabling kde because cov matrix is singular for objectives specificity & auroc                 
/home/sunxd/anaconda3/lib/python3.9/site-packages/seaborn/axisgrid.py:1690: UserWarning: Starting a Matpl
otlib GUI outside of the main thread will likely fail.                                                   
  f = plt.figure(figsize=(height, height))                                                               
/home/sunxd/anaconda3/lib/python3.9/site-packages/seaborn/axisgrid.py:1690: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  f = plt.figure(figsize=(height, height))
WARNING: disabling kde because cov matrix is singular for objectives f1 & auroc
/home/sunxd/anaconda3/lib/python3.9/site-packages/seaborn/axisgrid.py:1690: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  f = plt.figure(figsize=(height, height))
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/sunxd/anaconda3/lib/python3.9/tkinter/__init__.py", line 842, in after_cancel
    data = self.tk.call('after', 'info', id)
RuntimeError: main thread is not in main loop

**Comment by smilesun** [comment]
but at least I could get all the plots, if "tkagg" also works on your side, I will change that in the branch.

**Comment by smilesun** [comment]
see here: https://github.com/marrlab/DomainLab/pull/133

**Comment by schoersch** [comment]
> what backend are you using? @Car-la-F
> 
> https://matplotlib.org/stable/users/explain/backends.html

Regarding the matplotlib documentation, it should be most stable if we use a non-interactive backend, i.e. one from the first table. Since we are currently plotting to png, this would be "agg".
