### ISSUE TITLE
build automatic dependencies installation solution for domainlab and snakemake

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#105]
from the official documentation of snakemake, https://snakemake.readthedocs.io/en/stable/getting_started/installation.html
the dependencies are installed via conda and mamba. 

For ease of user, either we want a docker or another dependencies resolution scheme for one line command installation

@schoersch , @xinyuejohn , how have you installed snakemake on the cluster? also using mamba? or a minimal installation via pip works as well? 

Since mamba will create new conda environment, then one have to install all dependencies of DomainLab into the new conda environment?

**Comment by rahulbshrestha** [comment]
@smilesun Currently, snakemake is installed using pip on the cluster. Maintaing a single "requirements.txt" for pip installations should be enough, right?
