### ISSUE TITLE
how do i specify options like --no_cu, --no_dump in benchmark? 

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#118]
https://github.com/marrlab/DomainLab/blob/e918dd21bb310da2473b2d1ac90d7c2a2280586d/examples/yaml/demo_benchmark.yaml#L6

@RahelehSalehi @schoersch

**Comment by schoersch** [comment]
With
`nocu: True` and `no_dump: True`

Note that there is a typo in the title, it is `nocu`, without _.
