### ISSUE TITLE
matchdg on gpu

### ISSUE THREAD

**Issue by schoersch** [marrlab/DomainLab#123]
@smilesun I'm currently checking the config yaml for all algorithms on the denbi cluster. Doing so I noticed that for matchdg, a process is created on the GPU, but computations of this process are carried out nearly completely on the cpu. Is it running on gpu on your machine? Or is this algorithm supposed to be mainly on the cpu?

**Comment by smilesun** [comment]
@schoersch, have you used continuous monitoring for the GPU load? e.g. nvidia-smi -f or something? 
My guess is there has been a lot of operations needed using cpu for matchdg (the matching process), but the neural network operation is using GPU so I would assume you can observe a oscillating behavior of the GPU load when running match-dg?

**Comment by schoersch** [comment]
@smilesun yes, I had oscillating behavior, gpu was used up to 25% by matchdg from time to time. So it seems fine/expected
