### ISSUE TITLE
Printing model name

### ISSUE THREAD

**Issue by schoersch** [marrlab/DomainLab#127]
@smilesun is it possible to print also the model name in this statement? With multithreading it is not possible to say to which algorithm this print refers.

https://github.com/marrlab/DomainLab/blob/37504b0d51b241076ab86374dfa5727bfec7b315/domainlab/compos/exp/exp_main.py#L50

**Comment by smilesun** [comment]
[8136a87](https://github.com/marrlab/DomainLab/commit/8136a8725a82c28192d3a990b5506063086c430f)
