### ISSUE TITLE
sanity check for blood image dataset

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#128]

**Comment by schoersch** [comment]
Regarding the dataset on denbi:
evaluating the sanity check images, I decided with @Car-la-F to:

1. remove RandomSizedCrop and RandomGrayscale from the transformations
2. reduce ColorJitter from 0.3 to 0.03

this is also motivated by https://github.com/marrlab/DomainLab/issues/121#issuecomment-1435726151.

@xinyuejohn @rahulbshrestha you can obtain these changes by cherry-picking a5228609.
