### ISSUE TITLE
jigen failure

### ISSUE THREAD

**Issue by schoersch** [marrlab/DomainLab#129]
```
RuleException:                                               
IndexError in file /home/ubuntu/georg/DomainLab/domainlab/exp_protocol/benchmark.smk, line 59:                             
index 9 is out of bounds for axis 0 with size 9              
  File "/home/ubuntu//DomainLab/domainlab/exp_protocol/benchmark.smk", line 59, in __rule_run_experiment              
  File "/home/ubuntu/DomainLab/domainlab/exp_protocol/run_experiment.py", line 87, in run_experiment                 
  File "/home/ubuntu/DomainLab/domainlab/compos/exp/exp_main.py", line 48, in execute                                
  File "/home/ubuntu/DomainLab/domainlab/algos/trainers/train_visitor.py", line 43, in tr_epoch                      
  File "/home/ubuntu/DomainLab/domainlab/algos/trainers/train_basic.py", line 26, in tr_epoch                        
  File "/home/ubuntu/mambaforge/envs/gdl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
  File "/home/ubuntu/mambaforge/envs/gdl/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 721, in _next_da
ta                                                                                                                         
  File "/home/ubuntu/mambaforge/envs/gdl/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch  
  File "/home/ubuntu/mambaforge/envs/gdl/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listco
mp>                                                                                                                        
  File "/home/ubuntu/mambaforge/envs/gdl/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 235, in __getitem__
  File "/home/ubuntu/DomainLab/domainlab/dsets/utils_wrapdset_patches.py", line 108, in __getitem__                  
  File "/home/ubuntu/DomainLab/domainlab/dsets/utils_wrapdset_patches.py", line 108, in <listcomp>                   
  File "/home/ubuntu/mambaforge/envs/gdl/lib/python3.8/concurrent/futures/thread.py", line 57, in run                      
Shutting down, this might take some time.                                                                                  Exiting because a job execution failed. Look above for error message
```

**Comment by Car-la-F** [comment]
reproducible with 

```
tpath: examples/tasks/task_vlcs.py  # dataset

test_domains:
  - caltech

output_dir: zoutput/benchmarks/demo_benchmark

num_param_samples: 2
sampling_seed: 1  # Optional

epos: 3
bs: 2
startseed: 1
endseed: 2  # currently included

Task4:  # name
  aname: jigen

  hyperparameters:
    nperm:
      distribution: categorical
      values:
        - 30
        - 31
        - 100
      datatype: int

    pperm:
      min: 0.1
      max: 0.5
      distribution: uniform

    grid_len:
      min: 2
      max: 5
      step: 1
      distribution: uniform

    early_stop:
      distribution: categorical
      datatype: int
      values:
        - 1
        - 5
        - 10

    gamma_reg:
      min: 0.01
      max: 10
      distribution: loguniform
```

command:
`snakemake --cores 1 -s "domainlab/exp_protocol/benchmark.smk" --configfile "examples/yaml/demo_benchmark.yaml"`

**Comment by smilesun** [comment]
@Car-la-F @schoersch , i am back to work an hour ago, I have added some tests to jigen, and try to reproduce now:

using 

git checkout carla_benchmark
snakemake --cores 1 -s "domainlab/exp_protocol/benchmark.smk" --configfile "examples/yaml/demo_benchmark.yaml"

**Comment by smilesun** [comment]
What I got:  will take sometime to delve deep into it

```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                   count    min threads    max threads
------------------  -------  -------------  -------------
agg_results               1              1              1
all                       1              1              1
parameter_sampling        1              1              1
run_experiment            5              1              1
total                     8              1              1

Select jobs to execute...

[Tue Feb 21 15:41:15 2023]
rule parameter_sampling:
    input: /home/sunxd/domainlab_master/examples/yaml/demo_benchmark.yaml
    output: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    jobid: 3
    reason: Missing output files: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    resources: tmpdir=/tmp

[Tue Feb 21 15:41:15 2023]
Finished job 3.
1 of 8 steps (12%) done
Select jobs to execute...

[Tue Feb 21 15:41:15 2023]
rule run_experiment:
    input: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    output: zoutput/benchmarks/demo_benchmark/rule_results/1.csv
    jobid: 4
    reason: Missing output files: zoutput/benchmarks/demo_benchmark/rule_results/1.csv; Input files updated by another job: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    wildcards: index=1
    resources: tmpdir=/tmp

[Tue Feb 21 15:42:25 2023]
Finished job 4.
2 of 8 steps (25%) done
Select jobs to execute...

[Tue Feb 21 15:42:25 2023]
rule run_experiment:
    input: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    output: zoutput/benchmarks/demo_benchmark/rule_results/2.csv
    jobid: 5
    reason: Missing output files: zoutput/benchmarks/demo_benchmark/rule_results/2.csv; Input files updated by another job: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    wildcards: index=2
    resources: tmpdir=/tmp

[Tue Feb 21 15:44:21 2023]
Finished job 5.
3 of 8 steps (38%) done
Select jobs to execute...

[Tue Feb 21 15:44:21 2023]
rule run_experiment:
    input: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    output: zoutput/benchmarks/demo_benchmark/rule_results/3.csv
    jobid: 6
    reason: Missing output files: zoutput/benchmarks/demo_benchmark/rule_results/3.csv; Input files updated by another job: zoutput/benchmarks/demo_benchmark/hyperparameters.csv
    wildcards: index=3
    resources: tmpdir=/tmp

Removing output files of failed job run_experiment since they might be corrupted:
zoutput/benchmarks/demo_benchmark/rule_results/3.csv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-02-21T154115.105733.snakemake.log
```

**Comment by schoersch** [comment]
@smilesun 
I think jigen is no part of this demo. I created the jigen_failure, which reproduces the error above via

git checkout jigen_failure
snakemake --cores 1 -s "domainlab/exp_protocol/benchmark.smk" --configfile examples/yaml/jigen_test.yaml

**Comment by smilesun** [comment]
thanks, i merged master into Jigen to say if there will be a difference
`https://github.com/marrlab/DomainLab/pull/130` , will check

**Comment by smilesun** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'examples/yaml/jigen_test.yaml'

**Comment by smilesun** [comment]
> I get a different error:
> 
> ```
> RuleException:
> NotImplementedError in file /home/carla/Dokumente/Uni/Master/Computational_Methods_for_Single-Cell_Biology/DomainLab/domainlab/exp_protocol/benchmark.smk, line 59:
> Namespace(config_file=None, lr=0.0001, gamma_reg=0.08072307884499755, es=10, seed=1, nocu=False, gen=False, keep_model=False, epos=3, epo_te=1, debug=False, dmem=False, no_dump=True, out='zoutput', dpath='zdpath', tpath='examples/tasks/task_vlcs.py', npath=None, npath_dom=None, npath_argna2val=None, nname_argna2val=None, nname=None, nname_dom=None, apath=None, exptag='exptag', aggtag='aggtag', msel=None, aname='jigen', acon=None, task=None, bs=2, split=0, te_d='caltech', tr_d=None, san_check=False, san_num=8, zd_dim=64, zx_dim=0, zy_dim=64, topic_dim=3, topic_h_dim=8, img_h_dim=8, nname_topic_distrib_img2topic=None, npath_topic_distrib_img2topic=None, nname_encoder_sandwich_layer_img2h4zd=None, npath_encoder_sandwich_layer_img2h4zd=None, gamma_y=None, gamma_d=None, beta_t=1.0, beta_d=1.0, beta_x=1.0, beta_y=1.0, warmup=100, tau=0.05, epos_per_match_update=5, epochs_ctr=None, epochs_erm=None, penalty_ws=0.1, nperm=31, pperm=0.49887392437554745, grid_len=5, dial_steps_perturb=3, dial_noise_scale=0.001, dial_lr=0.003, dial_epsilon=0.031, result_file='zoutput/benchmarks/demo_benchmark/rule_results/0.csv', params={'nperm': 31, 'pperm': 0.49887392437554745, 'grid_len': 5, 'early_stop': 5, 'gamma_reg': 0.08072307884499755}, benchmark_task_name='Task4', param_index=0) does not exist
>   File "/home/carla/Dokumente/Uni/Master/Computational_Methods_for_Single-Cell_Biology/DomainLab/domainlab/exp_protocol/benchmark.smk", line 59, in __rule_run_experiment
>   File "/home/carla/Dokumente/Uni/Master/Computational_Methods_for_Single-Cell_Biology/DomainLab/domainlab/exp_protocol/run_experiment.py", line 85, in run_experiment
>   File "/home/carla/Dokumente/Uni/Master/Computational_Methods_for_Single-Cell_Biology/DomainLab/domainlab/compos/exp/exp_main.py", line 33, in __init__
>   File "/home/carla/Dokumente/Uni/Master/Computational_Methods_for_Single-Cell_Biology/DomainLab/domainlab/algos/builder_jigen1.py", line 33, in init_business
>   File "/home/carla/Dokumente/Uni/Master/Computational_Methods_for_Single-Cell_Biology/DomainLab/domainlab/compos/zoo_nn.py", line 42, in __call__
>   File "/home/carla/Dokumente/Uni/Master/Computational_Methods_for_Single-Cell_Biology/DomainLab/domainlab/compos/pcr/p_chain_handler.py", line 84, in handle
>   File "/home/carla/Dokumente/Uni/Master/Computational_Methods_for_Single-Cell_Biology/DomainLab/domainlab/compos/pcr/p_chain_handler.py", line 84, in handle
>   File "/home/carla/Dokumente/Uni/Master/Computational_Methods_for_Single-Cell_Biology/DomainLab/domainlab/compos/pcr/p_chain_handler.py", line 84, in handle
>   File "/home/carla/Dokumente/Uni/Master/Computational_Methods_for_Single-Cell_Biology/DomainLab/domainlab/compos/pcr/p_chain_handler.py", line 88, in handle
>   File "/home/carla/miniconda3/envs/DomainLab/lib/python3.9/concurrent/futures/thread.py", line 58, in run
> ```
> 
> reproducible with:
> 
> ```
> tpath: examples/tasks/task_vlcs.py  # dataset
> 
> test_domains:
>   - caltech
> 
> output_dir: zoutput/benchmarks/demo_benchmark
> 
> num_param_samples: 2
> sampling_seed: 1  # Optional
> 
> epos: 3
> bs: 2
> startseed: 1
> endseed: 2  # currently included
> 
> Task4:  # name
>   aname: jigen
> 
>   hyperparameters:
>     nperm:
>       distribution: categorical
>       values:
>         - 30
>         - 31
>         - 100
>       datatype: int
> 
>     pperm:
>       min: 0.1
>       max: 0.5
>       distribution: uniform
> 
>     grid_len:
>       min: 2
>       max: 5
>       step: 1
>       distribution: uniform
> 
>     early_stop:
>       distribution: categorical
>       datatype: int
>       values:
>         - 1
>         - 5
>         - 10
> 
>     gamma_reg:
>       min: 0.01
>       max: 10
>       distribution: loguniform
> ```
> 
> command: `snakemake --cores 1 -s "domainlab/exp_protocol/benchmark.smk" --configfile "examples/yaml/demo_benchmark.yaml"`

I can reproduce this one

**Comment by smilesun** [comment]
@Car-la-F @schoersch 
by adding one line:
`nname: alexnet `
to example yaml file I could get the following error

```
index 9 is out of bounds for axis 0 with size 9
  File "/home/sunxd/domainlab_master/domainlab/exp_protocol/benchmark.smk", line 59, in __rule_run_experiment
  File "/home/sunxd/domainlab_master/domainlab/exp_protocol/run_experiment.py", line 87, in run_experiment
  File "/home/sunxd/domainlab_master/domainlab/compos/exp/exp_main.py", line 48, in execute
  File "/home/sunxd/domainlab_master/domainlab/algos/trainers/train_visitor.py", line 43, in tr_epoch
  File "/home/sunxd/domainlab_master/domainlab/algos/trainers/train_basic.py", line 26, in tr_epoch
  File "/home/sunxd/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
  File "/home/sunxd/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
  File "/home/sunxd/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
  File "/home/sunxd/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
  File "/home/sunxd/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 235, in __getitem__
  File "/home/sunxd/domainlab_master/domainlab/dsets/utils_wrapdset_patches.py", line 108, in __getitem__
  File "/home/sunxd/domainlab_master/domainlab/dsets/utils_wrapdset_patches.py", line 108, in <listcomp>
  File "/home/sunxd/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.

```

**Comment by smilesun** [comment]
@Car-la-F @schoersch , thanks for finding the bug! I am sorry for my carelessness, we can not support other grid-len other than 3*3 currently! 
So we have to remove 

```
    grid_len:
      min: 2
      max: 5
      step: 1
      distribution: uniform

```
