### ISSUE TITLE
specify split or not in b_task

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#135]
https://github.com/marrlab/DomainLab/blob/66a71317a7d14908304da60eb6c2d1f7b5bd1843/domainlab/tasks/b_task.py#L71

https://github.com/marrlab/DomainLab/blob/1a7cd6513836217aa8ba231d3564ffc7e369bd58/domainlab/tasks/b_task.py#L72

@agisga , maybe we can have some discussions here to avoid using default arguments but pass the argparser value to the funciton here whether to split or not.

If split=False, for task folder, it generate validation set identical to the train set

**Comment by agisga** [comment]
> @agisga , maybe we can have some discussions here to avoid using default arguments but pass the argparser value to the funciton here whether to split or not.

I think that's a good idea. Not sure if it will lead to something breaking though...

**Comment by smilesun** [comment]
I guess we have to then fix the potential failures then

**Comment by smilesun** [comment]
fixed
