### ISSUE TITLE
change end-seed to num_see and pass start seed as an argument from command line to snakemake

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#137]
I think it is crutial to have this feature so that we can use different start seed from different machines to replicate stochastic variation.

@schoersch , i will do this, but if you could offer some minor hint, that could speed up my work

**Comment by schoersch** [comment]
The smk file is fully operable Python. Thus, you can access the command line arguments via `sys.argv`.
The yaml file passed with `--configfile` is parsed by snakemake and provided as dict in the global variable `config`.

**Comment by schoersch** [comment]
https://github.com/marrlab/DomainLab/blob/5c5df06aff8b3446785fc48d6e7d06149dcbeb81/domainlab/exp_protocol/run_experiment.py#L109

This is then of course the line which needs to be adapted.

**Comment by smilesun** [comment]
see pr: https://github.com/marrlab/DomainLab/pull/144

**Comment by smilesun** [comment]
fixed in [2bc34e4](https://github.com/marrlab/DomainLab/commit/2bc34e42438fc88bb50b722bac024517237ab5f3)
