### ISSUE TITLE
Sanity check does not respect tr_d and te_d

### ISSUE THREAD

**Issue by schoersch** [marrlab/DomainLab#148]
running only an a subset of the data using `--tr_d`,  `--san_check` is generating images for all domains of the dataset. E.g.
```
python main_out.py --tr_d 0 1 2 --san_check --debug --te_d=3 --task=mnistcolor10 --aname=diva --nname=conv_bn_pool_2 --nname_dom=conv_bn_pool_2 --gamma_y=10e5 --gamma_d=1e5
```
gives all 10 domains in Dset_extraction.

**Comment by smilesun** [comment]
fixed with 9658b3a
