### ISSUE TITLE
suggestion: add a functionality to produce the txt files automatically

### ISSUE THREAD

**Issue by aliechoes** [marrlab/DomainLab#15]
it makes sense to provide the possibility for the users to either pass their own txt files (including the files and their classes as well dataset) or the code does this automatically for them.  
For example, if I have multiple datasets which are already in the correct folder structure, the code could simply read and create the right table of files for them

**Comment by smilesun** [comment]
https://marrlab.github.io/DomainLab/html/doc_tasks.html
