### ISSUE TITLE
partial aggregation does not work

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#152]
apend the following to the end of the file examples/benchmark/run_snakemake.sh, 
now i want to test the rule 

--allowed-rules agg_partial_results

works with 

`snakemake --cores 1 -s "domainlab/exp_protocol/benchmark.smk" --configfile "examples/yaml/demo_benchmark.yaml" --keep-going --allowed-rules agg_partial_results`
I got

```
Building DAG of jobs...
total_num_params=5
=2 * 2 + 1
MissingInputException in rule agg_results in file /home/sunxd/DomainLab/domainlab/exp_protocol/benchmark.smk, line 96:
Missing input files for rule agg_results:
    output: zoutput/benchmarks/demo_benchmark/results.csv
    affected files:
        zoutput/benchmarks/demo_benchmark/rule_results/2.csv

```

**Comment by schoersch** [comment]
@smilesun It seems to me, that there is no intuitive way for aggregating partial results with snakemake.
At least when I'm trying this, often reruns of some rules are triggered, you have to clean up with incomplete files etc.

I think it would be best to add a command line argument to Domainlab, which, given the benchmark config, aggregates all available results and generates the graphs. However, I don't know how this is on clusters.
