### ISSUE TITLE
add confusion matrix after the training

### ISSUE THREAD

**Issue by aliechoes** [marrlab/DomainLab#17]

**Comment by xinyuejohn** [comment]
@smilesun @aliechoes At the moment, aggregated results are saved in zoutput/aggrst after each run. Do you mean we also save the confusion matrix here, or just print it in the console?

**Comment by aliechoes** [comment]
I think it is meant to plot and save the CM

**Comment by smilesun** [comment]
@aliechoes , do you think this issue is the same amount of work as https://github.com/marrlab/DomainLab/pull/59?

**Comment by smilesun** [comment]
is this still work in progress?  @xinyuejohn
