### ISSUE TITLE
--san_check should take into account --tr_d and --te_d

### ISSUE THREAD

**Issue by agisga** [marrlab/DomainLab#174]
--san_check should use the information about which domains are used for training and which are used for testing, rather than reporting on all domains.

https://github.com/marrlab/DomainLab/blob/ed190df5ae0be81722e5a7d31bccad54e1aa5528/domainlab/compos/exp/exp_main.py#L68

This is useful for the case when only some but not all of the domains are used.

**Comment by smilesun** [comment]
#148 mentioned the same issue

**Comment by smilesun** [comment]
Fixed in 9658b3a
