### ISSUE TITLE
write domain generalization on color mnist into documentation and show an algorithm which works better than deepall

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#219]
make a markdown file which document 
1. an image of comparing color mnist from different domains and how to get this done from domainlab via --sanitycheck
2. how to do classification using deepall from domainlab
3. how to do classification using diva, write the commandline (find a hyper-parameter that diva works better than deepall)
4. show the conterfactorial image generation of different domains of diva.

**Comment by Car-la-F** [comment]
@smilesun 

I started a markdown file on the branch `cf_colorMNIST_doc` in `docs/doc_MNIST_classification.md`. I got until the point where I start to write about the image generation of diva. I also uploaded all images which are generated by dive using the `--gen` keyword (they can be found in `docs/figs/colored_MNIST/gen_...`). 

I realised I have no idea how the images are generated exactly: I know that the generation is done by modifying the latent representation, for example by changing the latent variable for the domain, but I don't know how I can interpret the filenames to know how the latent space was modified. 

Maybe you can have a look and point some thinks out.
