### ISSUE TITLE
website column examples, create copy button for user to copy the whole command

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#229]

**Comment by Car-la-F** [comment]
@smilesun,
can you provide any tutorial/webpage explaining how one can do this?

**Comment by smilesun** [comment]
No, i don't know yet, i guess it might be due to some configuration in your documenation package:
actually for markdown this is automatic:  for instance: https://github.com/marrlab/DomainLab/blob/master/docs/doc_tasks.md

but this issue is not priority if we could not find a clue how to do this soon.
