### ISSUE TITLE
tune learning rate for domainbed resnet50

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#233]
in domainbed:  10Uniform(−5,−3.5), in their paper, they reported a much higher acc, though when we used their modified version of resnet, we could not get that accuracy. The task is to use only deepall, but use grid search to find a learning rate that works the best.

**Comment by smilesun** [comment]
it seems even with random search of learning rate, the accuracy is maximum 70%, not 80% as the domainbed paper claimed

**Comment by Car-la-F** [comment]
I looked into the weights used for resnet. It seems like the approach of loading the weights is outdated and always gave a warning when running the code. I fixed this and also found that it loaded only the second best performing weights. I changed this to the best performing weights and created a pull request. Maybe you can check with the new weights

Pull request #274
