### ISSUE TITLE
write a script to test all command lines in the documentation works

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#248]
We have several markdown files in our doc folder, those will be casted into html file by a python package, we need to check everything we wrote in the markdown file works, this has been down for doc_examples.md already, see below

#!/bin/bash -x -v
set -e  # exit upon first error

sed 's/`//g' docs/doc_examples.md > ./sh_temp.sh   # this line will extract all the commandline from a markdown file, here named docs/doc_examples.md,  to a new file called sh_temp.sh

bash -x -v -e sh_temp.sh    # then we just execute this sh_temp.sh to check if the command there works. 

The task here is to provide a similar script file like https://github.com/marrlab/DomainLab/blob/master/ci_run_examples.sh

**Comment by Car-la-F** [comment]
@smilesun 
Can you test if the skript in ci_run_examples.sh does work? 
Because if so, then I think this issue is completed

**Comment by smilesun** [comment]
oh, i did not test, but i will do later.

**Comment by smilesun** [comment]
@Car-la-F , it does not work yet. Could you annotate some script not to be shell? For example for our slurm benchmark script, it is not possible to test locally if slurm is not installed. 

I have splited each markdown file extracted shell, could you test them one by one?

**Comment by Car-la-F** [comment]
@smilesun 
looking at the examples, it seems like it will take forever to test them on my Laptop. Isn't it more eficient to test it in the cluster?

**Comment by Car-la-F** [comment]
Also my installation may deviate from what is on the cluster. E.g. I do have snakemake installed as I did run some of the benchmarks on the laptop

**Comment by Car-la-F** [comment]
Additionally I think we need to add `> ./sh_temp_example.sh` after executing the examples to empty the files. Othervise it seems like they will be extended each time one likes to test
