### ISSUE TITLE
inconsistency in doc_MNIST_classification.md

### ISSUE THREAD

**Issue by Car-la-F** [marrlab/DomainLab#255]
I found an inconsistency in `doc_MNIST_classification.md` in the last paragraph:

The text says that deepall needs more iterations than diva, but the tabel says that deepall needs 9 iterations while diva needs 16. @smilesun Did you rerun the experiments and adapted the values in the tabel? I'm asking because I'm very sure in my experiments deepall had by far more iterations, but I did run on faulty code, so might be that my results were simply wrong

**Comment by smilesun** [comment]
Hi, yes, I rerun the experiment with another model selection criteria.  I think in that markdown file we should avoid too detailed information so that we dont have to update them too often.

**Comment by smilesun** [comment]
fixed in https://github.com/marrlab/DomainLab/commit/871f76cd21748a8acbb462be182e9a1620da751d
