### ISSUE TITLE
reference wrong in DIAL documentation

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#260]
https://marrlab.github.io/DomainLab/build/html/docDIAL.html

Our dial should be a paper published in transactions in machine learning i belive?

**Comment by Car-la-F** [comment]
@smilesun,
I am not very sure what to put as a reference. Do you want a better link (i.e. not arxiv)? For this I only found this two links:
- https://openreview.net/forum?id=U8uJAUMzj9
- https://openreview.net/pdf?id=U8uJAUMzj9

One can also find the paper on the webside of transactions in machine learning (https://jmlr.org/tmlr/papers/), but it is just on point far down in the list of papers. If you click on the link it will lead you to the second link from above.

**Comment by Car-la-F** [comment]
@smilesun 

> @smilesun, I am not very sure what to put as a reference. Do you want a better link (i.e. not arxiv)? For this I only found this two links:
> 
>     * https://openreview.net/forum?id=U8uJAUMzj9
> 
>     * https://openreview.net/pdf?id=U8uJAUMzj9
> 
> 
> One can also find the paper on the webside of transactions in machine learning (https://jmlr.org/tmlr/papers/), but it is just on point far down in the list of papers. If you click on the link it will lead you to the second link from above.

**Comment by smilesun** [comment]
If you click on the link on the website, it direct to an old paper

**Comment by Car-la-F** [comment]
@smilesun 
I don't see anything wrong with the paper at the link in the git documentation (https://arxiv.org/pdf/2104.00322.pdf). It is also the same as the paper at this link https://openreview.net/pdf?id=U8uJAUMzj9

**Comment by smilesun** [comment]
@Car-la-F 
this sentence in the html:
`
Figure 1: adversarial domain (Image source: Figure 1 of Explaining and Harnessing Adversarial Examples https://arxiv.org/abs/1412.6572)`

**Comment by smilesun** [comment]
as explained, this is the image source

**Comment by smilesun** [comment]
as explained, this is the image source
