### ISSUE TITLE
Import domain lab into the custom script 

### ISSUE THREAD

**Issue by RaoUmer** [marrlab/DomainLab#265]

**Comment by smilesun** [comment]
For users who would like to use the DomainLab API to write their own application, we should give an example of which class/method to import, etc.

**Comment by smilesun** [comment]
from torchvision import models as torchvisionmodels
from torchvision.models import ResNet50_Weights

from domainlab.models.model_deep_all import mk_deepall
from domainlab.algos.trainers.trainer_mldg import TrainerMLDG

from domainlab.compos.nn_zoo.nn import LayerId
from domainlab.compos.nn_zoo.nn_torchvision import NetTorchVisionBase

**Comment by smilesun** [comment]
[dd86428](https://github.com/marrlab/DomainLab/commit/dd8642880ba0f991963a1c3f6d1c155b0c84a6a7)

**Comment by smilesun** [comment]
see example 

https://github.com/marrlab/DomainLab/blob/master/tests/test_mk_exp.py
