### ISSUE TITLE
problems when installing reuirements with pip install -r requirements

### ISSUE THREAD

**Issue by Car-la-F** [marrlab/DomainLab#267]
When installing the requirements have issues installing 

- pillow -> changing to `pillow==9.3.0 ; python_version >= "3.9" and python_version < "4.0"` resolved the problem

**Comment by smilesun** [comment]
[164fe2a](https://github.com/marrlab/DomainLab/commit/164fe2af5ad0ef51e5ac4444aa63f66413acdbc4)
