### ISSUE TITLE
let train and test set to use different transformations

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#3]

**Comment by aliechoes** [comment]
in this case, it is better to be able to create different 'torch.datasets'

**Comment by aliechoes** [comment]
for example, this gives a huge benefit by providing the possibility of trying different augmentations or dataset specific changes

**Comment by smilesun** [comment]
@aliechoes , please try if this works for you:

https://github.com/marrlab/DomainLab/tree/task_loader

**Comment by rahulbshrestha** [comment]
@smilesun is this issue already fixed? I noticed you have a solution in task_loader branch. If not, what else is there yet to do?

**Comment by smilesun** [comment]
@rahulbshrestha 

1. https://github.com/marrlab/DomainLab/pull/19

1. 1This branch need test 
1. 2 and documentation for which to show Ali's issue has been addressed, e.g. use different transformations and write in documentaiton.

2. For task PathList below, it is not yet supported to have different transformation yet. 

https://github.com/marrlab/DomainLab/blob/master/examples/tasks/demo_task_path_list_small.py

**Comment by smilesun** [comment]
fixed
