### ISSUE TITLE
generate benchmark using branch shared parameters  for mnist

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#354]
https://github.com/marrlab/DomainLab/pull/328

**Comment by smilesun** [comment]
one could post the benchmark results here.

**Comment by lisab00** [comment]
tested the file "benchmark_mnist_shared_hyper_grid.yaml" on branch "cf_bugfix_benchmark_yaml".

This is the output:

<img width="1053" alt="image" src="https://github.com/marrlab/DomainLab/assets/73993822/37775fc5-3737-4243-b861-82d9de796515">

**Comment by smilesun** [comment]
@lisab00 , 
that does not seem to be the right branch,

the correct branch should be 

cf_common_hyperparam_sampling

**Comment by lisab00** [comment]
Update: on branch "cf_common_hyperparam_sampling" the full benchmark was completed (including aggregated results and graphics)

**Comment by smilesun** [comment]
so how does the result look like? Maybe if you post it here, it is easier to see if the results make sense? e.g. we will know the accuracy distribution?

**Comment by lisab00** [comment]
[results.csv](https://github.com/marrlab/DomainLab/files/12595608/results.csv)
![stochastic_variation](https://github.com/marrlab/DomainLab/assets/73993822/d0b96d3a-d820-412d-8a9a-9d347c6d6c5a)
[hyperparameters.csv](https://github.com/marrlab/DomainLab/files/12595609/hyperparameters.csv)

I realized that the benchmark only obtained results for the diva model. No model was trained for hduva model, although hyperparameters have been sampled correctly. I will have a look at the log files

**Comment by smilesun** [comment]
maybe that is the bug C has explained to me?  one need a manual run to accumulate all the results? 
To verfy that, one could look how many csv files are there in the rules folder, if they is the same with number of hyperparameters

**Comment by lisab00** [comment]
There are only 9 files in the rule results folder, corresponding to index 0-8 (see results.csv from previous comment). So the experiments for the other hyp.param combinations were not performed.
I probably cannot manually accumulate the results if they're not in the rules folder....

Maybe it's worth noting that I performed the same benchmark twice and both times only indices 0-8 were performed and the benchmarks "stopped" at exactly the same point".

**Comment by smilesun** [comment]
that means those jobs have not been run at all, but snakemake said everything is alright, all jobs completed?

**Comment by lisab00** [comment]
snakemake reports some errors, but only in the output files which have been created (e.g. in rule results 7.csv). I attach the snakemake file.
[2023-09-13T094708.347463.snakemake.log](https://github.com/marrlab/DomainLab/files/12596724/2023-09-13T094708.347463.snakemake.log)

**Comment by smilesun** [comment]
`Error executing rule run_experiment on cluster (jobid: 11, external: Submitted batch job 13448516, "`

so the log file corresponding to 13448516 will contain the error message then,  under folder logs in the root diretory.

**Comment by lisab00** [comment]
<img width="1061" alt="image" src="https://github.com/marrlab/DomainLab/assets/73993822/c3fc343f-0d0d-4b13-8da8-b23f46fd8ae4">

That's what it says. But as this only concerns the bencmark in the rule results 7.csv file, I don't understand why the experiments are not performed for any hyperparameters from index 9 on.

**Comment by smilesun** [comment]
@lisab00 , this seems to be a bug in diva and hduva, we probalby should use another yaml file to test the benchmark, maybe with your written one.

**Comment by smilesun** [comment]
@Car-la-F , this is a yaml file Lisa has written, https://github.com/marrlab/DomainLab/pull/348/files
could you maybe test if the shared parameter version will work by producing an example benchmark experiment? It should finish within a few hours on the cluster.

**Comment by smilesun** [comment]
@lisab00 , so first generate benchmark for mnist, there are al
