### ISSUE TITLE
reproduce benchmark on pacs dataset

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#370]
![stochastic_variation_two_rows](https://github.com/marrlab/DomainLab/assets/570694/51dfed74-5017-4da2-a36f-452817f01ead)

step 1. Use the branch xd_refactor_reg_loss_separate_multipler to do the benchmark with yaml file:

https://github.com/marrlab/DomainLab/blob/master/examples/benchmark/benchmark_pacs_resnet.yaml

there might be mistakes in this file

step 2. on the new benchmark facility branch with functionality for shared parameters to rewrite a grid search version of 
https://github.com/marrlab/DomainLab/blob/master/examples/benchmark/benchmark_pacs_resnet.yaml

comment: one could also use separate yaml files like

https://github.com/marrlab/DomainLab/blob/master/examples/benchmark/benchmark_pacs_resnet_combo.yaml

and 
https://github.com/marrlab/DomainLab/blob/master/examples/benchmark/benchmark_pacs_resnet_nocombo.yaml

also, one has to check if this works.

**Comment by lisab00** [comment]
fyi @Car-la-F , I'm currently running the benchmark for step 1

**Comment by lisab00** [comment]
@smilesun
step 1:
there seems to be a bug in diva maybe, because the diva experiments keep failing (for both Carla and me) with an "NotImplementedError". But the rest of the benchmark is running through fine, rn it's at ~12%

**Comment by smilesun** [comment]
I found the bug, because "npath_dom" is not specified for DIVA. please add it to the yaml file. 

Use mnist first to create a benchmark plot and post the result here.

**Comment by smilesun** [comment]
@Car-la-F , now only need to use master, other branch has been merged.

**Comment by Car-la-F** [comment]
@smilesun the benchmark is running, it will not finish today though

**Comment by smilesun** [comment]
this might fix the bug one has encountered where diva and hduva has mismatch in its z dimension with the one saved on disk
https://github.com/marrlab/DomainLab/pull/468

**Comment by Car-la-F** [comment]
@smilesun 
The benchmark on the pacs dataset is finished. Somehow there is still a bug in diva. None of the experiments with diva were successful. However, all others did finish, so to complete the benchmark one only needs to rerun the diva part.

This are the results:

![stochastic_variation](https://github.com/marrlab/DomainLab/assets/79590443/0699a6f4-2b09-43d6-b2b6-d8841f495421)
