### ISSUE TITLE
create benchmark yaml file for fbopt using grid search

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#371]
The hyperparameters for fbopt can be found at https://github.com/marrlab/DomainLab/blob/fbopt/domainlab/algos/trainers/args_fbopt.py

**Comment by lisab00** [comment]
@smilesun do you have any preferred dataset / task for this ?

**Comment by smilesun** [comment]
maybe mnist? since it is at the first step for testing purposes, but you can make a difficult mnist in the sense that you only use the same color for training, but a different color for testing , e.g. https://marrlab.github.io/DomainLab/build/html/doc_MNIST_classification.html
i will fix the documentation now

**Comment by smilesun** [comment]
the figure in the documentation is fixed now, it can give you a good hint how to make the generalization difficult

https://marrlab.github.io/DomainLab/build/html/doc_MNIST_classification.html

**Comment by lisab00** [comment]
I added a first draft. The hyperparameter sampling should work, but I am not sure whether I specified aname and trainer correctly

**Comment by smilesun** [comment]
I think they are correct, could you run a local benchmark for this? just to test if it works. If you need help to create a gpu node, let me know

**Comment by lisab00** [comment]
what do you mean by "local" benchmark @smilesun ?

**Comment by lisab00** [comment]
are you talking about this command : srun -p gpu_p --qos=gpu --gres=gpu:1 -t 12:00:00 --mem 32 --nice=10000 --pty bash

**Comment by smilesun** [comment]
@lisab00 ,  the above quesiton is resolved,
just to clarify
first 
1. ssh lisa.beer@gui03....x
2. in the console run 

srun -p gpu_p --qos=gpu --gres=gpu:1 -t 12:00:00 --mem 32 --nice=10000 --pty bash

**Comment by smilesun** [comment]
@lisab00 , compare with normal dann, and post the benchmark result here

**Comment by lisab00** [comment]
<img width="637" alt="image" src="https://github.com/marrlab/DomainLab/assets/73993822/774290ae-4f8e-42cd-ae7b-ea873e93ee40">

I'm getting this error

**Comment by smilesun** [comment]
My mistakes I should  not have merged it to master, I will try to fix it

**Comment by smilesun** [comment]
@lisab00 , sorry I withdraw:  I think the problem is fbopt is not updated with master, I just updated it.  Could you try again? 

this is why I suggested to run the benchmark first on a single gpu, because we never know if a single experiment could finish.

**Comment by lisab00** [comment]
when I try to run on a single node I get this:

<img width="850" alt="image" src="https://github.com/marrlab/DomainLab/assets/73993822/754f79be-8534-4a8a-ab6f-cecc1bb6ec7e">

**Comment by lisab00** [comment]
now I get this error... but the hyperparamters.csv file exists in my zouput folder:
<img width="887" alt="image" src="https://github.com/marrlab/DomainLab/assets/73993822/00084155-9f20-4c9c-9a82-1b46ba6868ee">

**Comment by smilesun** [comment]
strange, could you then check if benchmark mnist on the master branch works?

**Comment by smilesun** [comment]
i will test your branch on my local machine

**Comment by smilesun** [comment]
have you updated the branch?

**Comment by smilesun** [comment]
lb_benchm_fbopt does not seem to be updated after master was merged into fbopt

**Comment by lisab00** [comment]
> @lisab00 , on my local it saids TypeError in file /home/sunxd/domainlab/domainlab/exp_protocol/benchmark.smk, line 126: 'float' object cannot be interpreted as an integer File "/home/sunxd/domainlab/domainlab/exp_protocol/benchmark.smk", line 126, in __rule_run_experiment File "/home/sunxd/domainlab/domainlab/exp_protocol/run_experiment.py", line 112, in run_experiment File "/home/sunxd/domainlab/domainlab/compos/exp/exp_main.py", line 65, in execute File "/home/sunxd/domainlab/domainlab/algos/trainers/train_fbopt.py", line 128, in tr_epoch File "/home/sunxd/domainlab/domainlab/algos/trainers/fbopt.py", line 52, in search_mu File "/home/sunxd/anaconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run Shutting down, this might take some time. Exiting because a job execution failed. Look above for error message Select jobs to execute...
> 
> [Fri Sep 15 12:20:06 2023]

You were right.I am now getting the exact sam emessage and all jobs fail.

**Comment by smilesun** [comment]
> have you updated the branch?

?

**Comment by smilesun** [comment]
> I think so

https://github.com/marrlab/DomainLab/pull/375, here it said the last update was yesterday, or we are talking about different branches?

**Comment by smilesun** [comment]
i am fixing a bug, this bug only exist in benchmark

**Comment by smilesun** [comment]
> i am fixing a bug, this bug only exist in benchmark

@lisab00 ,  my guess is in your yaml file 
https://github.com/marrlab/DomainLab/blob/b4b008a91b8b260a9930b27b1ca02c7ceed5f91d/examples/benchmark/test_benchmark_fbopt.yaml#L55

the hyperparameter should be a integer, that is what the error said, but the one generated seems to be float?

**Comment by smilesun** [comment]
maybe this will be helpful to you :

https://github.com/marrlab/DomainLab/pull/379/files

**Comment by lisab00** [comment]
yes in the new version you manually have to seet the datatype, I pushed a new version of the yaml file

**Comment by smilesun** [comment]
the new version works on my side

**Comment by lisab00** [comment]
[20.csv](https://github.com/marrlab/DomainLab/files/12619064/20.csv)

for me too, here is an generated csv file as example
