### ISSUE TITLE
grid search  yaml file should not have distribution for hyper-parameter

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#383]

**Comment by Car-la-F** [comment]
The distribution needs to be specified as it defines the spacing of the gird.
uniform -> equidistant spacing
normal -> gaussian sacing with more dense grid points around the mean
loguniform -> ...
lognormal -> ...

This is a feature which was added to the gridsearch to make it more powerful. Especially loguniform was very useful for all cases where the samples spanned over multiple orders of magnitudes
