### ISSUE TITLE
improve test coverage to 95%

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#40]
list all files that need to be improved for coverage and write test to cover them .

**Comment by prockenschaub** [comment]
- [x] `compos/exp/exp_main.py`: 19/36 (52.8%)
- [x] `models/model_custom.py`: 20/24 (83.3%) 
- [x] `arg_parser.py`: 44/51 lines (86.3%) 
- [ ] `compos/pcr/p_chain_handler.py`: 32/46 (69.6%)

**Comment by smilesun** [comment]
done
