### ISSUE TITLE
upload pacs and test the benchmark works

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#414]
make a symbolic link of the pacs dataset according to this file

https://github.com/marrlab/DomainLab/blob/master/examples/tasks/task_pacs_path_list.py

example symbolic link:
https://github.com/marrlab/DomainLab/blob/master/sh_pacs.sh

**Comment by smilesun** [comment]
https://github.com/marrlab/DomainLab/blob/7d71982aa995f43aed98da4a9ad6aa584c04575a/run_fbopt_pacs.sh

**Comment by e-dorigatti** [comment]
it's training on my end
