### ISSUE TITLE
Model Evaluation

### ISSUE THREAD

**Issue by doparmin** [marrlab/DomainLab#42]
1. After training a exptag.csv file is saved under /zoutput/aggrsts/.
This file lists names the test domain and lists the acc, f1-score and further values. 
Is the f1-score f1-micro or f1-macro?
There is also a prediction file for all images of the test set produced after training. The predictions should match with the numbers in the exptag.csv file, but are much lower. Which numbers are the correct ones?

**Comment by doparmin** [comment]
2. There should be simple examples to show how a saved model can be loaded and used for prediction.

**Comment by smilesun** [comment]
> 1. After training a exptag.csv file is saved under /zoutput/aggrsts/.
>    This file lists names the test domain and lists the acc, f1-score and further values.
>    Is the f1-score f1-micro or f1-macro?
https://github.com/marrlab/DomainLab/blob/master/domainlab/utils/perf_metrics.py
It is macro at the current commit. 
>    There is also a prediction file for all images of the test set produced after training. The predictions should match with the numbers in the exptag.csv file, but are much lower. Which numbers are the correct ones?
Could you provide an example of reproducing what you said?  What numbers are much lower?  The git commit should be exactly the same, the number of instances you have to count if the prediction file offers the same number of lines as the number of instances in the test set.

**Comment by smilesun** [comment]
> 2. There should be simple examples to show how a saved model can be loaded and used for prediction.

Do you want to make such an example and make a branch for that?

**Comment by doparmin** [comment]
[Dann_50.zip](https://github.com/marrlab/DomainLab/files/9794804/Dann_50.zip)
View for example this case of a 50 epochs long DANN run. Attached is the csv-file-output in the end (e.g. acc: 0.97857106) and for comparison the prediction on the test set. I computed the predictions and made a confusion matrix (e.g. acc: 0.7528). So it's of course very well possible I made a mistake somewhere. But currently I think that the numbers don't match up. So my question is how the output cdv-file is computed? Maybe not only out of domain but for all domains?

**Comment by doparmin** [comment]
[task_blood_hack.py.zip](https://github.com/marrlab/DomainLab/files/9794921/task_blood_hack.py.zip)
Task

**Comment by smilesun** [comment]
@doparmin Could you make a branch named "task_luke_armin "as I showed you last time and add this file you uploaded to the examples folder? In this way, people could look at your code even with a cellphone and comment on each line with a cellphone as well so you don't need to wait until someone has a laptop to download the file and open it. Also, you could make dynamic changes to your file without waiting for other to finish there comments

**Comment by smilesun** [comment]
@doparmin 
Can you try --task=blood_hack
use 

`python main_out.py --te_d=mllmar --tpath=examples/tasks/task_blood_hack.py --aname=dann --epos=50 --debug --bs=32 --npath=examples/nets/resnet.py --keep_model --task=blood_hack`

**Comment by smilesun** [comment]
using the commit 4adf1a739005b7ac775cf9646de99611e1025032, with command
`python main_out.py --te_d=caltech --tpath=examples/tasks/task_vlcs.py --debug --bs=2 --nname=alexnet --aname=diva --nname_dom=alexnet --gamma_y=7e5 --gamma_d=1e5
`
The output is 
[debug_e_mini_vlcs_te_caltech_diva_b4adf1a7_2022md_11md_11_16_35_38_seed_0_instance_wise_predictions.txt](https://github.com/marrlab/DomainLab/files/9991356/debug_e_mini_vlcs_te_caltech_diva_b4adf1a7_2022md_11md_11_16_35_38_seed_0_instance_wise_predictions.txt)

which correspond to 

`diva, 1, 0, aggtag, mname_debug_e_mini_vlcs_te_caltech_diva_b4adf1a7_2022md_11md_11_16_35_38_seed_0, commit_b4adf1a7, 0.82191783, 0.9015151, 0.675, 0.675, 0.7046374, 0.9728774
`
