### ISSUE TITLE
add notation in ell-vs-R plot, since it is hard to know which axis is ell , which is R loss in the phase plot

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#423]
ell is the task loss,    R is the regularization loss

**Comment by drEast** [comment]
Unfortunately, Tensorboard does not support custom labels. Even the ell-vs-R plot is a hacky solution, where I registered the task as "step". As far as i see, tensorboard only plots Y-value vs step and therefore does not allow custom labels.

**Comment by smilesun** [comment]
could you maybe then add it to the card name to indicate which is horizontal axis which is vertical axis? each plot has a name, there one could type anythign?

**Comment by drEast** [comment]
yes, sure

**Comment by drEast** [comment]
done in [342b343](https://github.com/marrlab/DomainLab/commit/342b34390008e3c49d576056e7bae60abc3153cf)
will pr together with penalized loss plot
