### ISSUE TITLE
improve setpiont of set point too low

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#424]
@ntchen , could you type some thoughts here if the set point is too low, how do we know it is too low, and how do we make it bigger?

**Comment by smilesun** [comment]
one solution is not to let set point sink too fast, see this pr: https://github.com/marrlab/DomainLab/pull/505

**Comment by smilesun** [comment]
the ultimate solution is:  we count how long the current R is higher than setpoing, if it last too long, then we set the setpoint to be the average of the R which will make the setpoint bigger, @ntchen ,what do you think? that is the only way which i can think  of to let mu converge.

**Comment by ntchen** [comment]
1) measuring if R is decreasing might be better. or 2) Perhaps we design another controller for setpoint to converge based on mu (I do not know how. it might be a bad idea).

The thing is that it is difficult to guess how long or how to define decreasing. It might be different from one loss/dataset to another, so we need hyperparameters. Fixed setpoints probably are not bad. If we remove this hyperparameter (fixed setpoint), we have to add other hyperparameters.

**Comment by smilesun** [comment]
@ntchen , this commit implement your point 1 measuring if R is decreasing 
commit c219302785d39ce941f79e775a73a3b34ee7c454

**Comment by ntchen** [comment]
I think we need to include a similar point as your idea as well:
(R is not decreasing) and (R>setpoint) and [3]

[3]: (mu == mu_max), or (mu is not increasing), or maybe we do not need this

**Comment by smilesun** [comment]
https://github.com/marrlab/DomainLab/blob/19e95f7b81e41b11be48482e649d0baa1724e09e/domainlab/algos/trainers/fbopt_setpoint_ada.py#L90

@ntchen , please re-open if issue persist
