### ISSUE TITLE
better tensorboard or other mechanism visualization of the phase plot of ell and R

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#427]
currently, Felix has hacked the tensorboard by plotting $\ell()$ vs $R()$ by making one of them to be iteration, this does not look nice sometimes, maybe there is a better way to do this.

It can also be true that we after enough iterations, the plot will look nice enough since we just use this plot for debugging at the moment, for paper, we need another mechansim to save the data. 

The task would be to investigate how can we save this phase portait plot somewhere and use seaborn to plot them later.

**Comment by smilesun** [comment]
An ideal plot for the paper looks like, here the $\mu$ in the plot has nothing to do with our paper, just to show what is a phase portrait

![image](https://github.com/marrlab/DomainLab/assets/570694/d928ef4e-cfbf-4e4c-a38a-693b82fa5ea1)

**Comment by smilesun** [comment]
run_fbopt_mnist.sh  this is fater to test @agisga

**Comment by agisga** [comment]
> An ideal plot for the paper looks like, here the mu in the plot has nothing to do with our paper, just to show what is a phase portrait

But we wouldn't get a full "phase portrait", right? Since we are only observing one trajectory of l vs R (unlike for phase portraits in ODEs where we know an analytic relationship between f and f' for example). Or am I misunderstanding something?

**Comment by smilesun** [comment]
We just plot the trajectory, there is no ode involved we just want to know
how the trajectory start and which direction it goes. Does it make sense?

**Comment by agisga** [comment]
> We just plot the trajectory, there is no ode involved we just want to know how the trajectory start and which direction it goes. Does it make sense?

Yes, I just wanted to confirm my understanding that there will be just a single trajectory shown (i.e., there won't be all the little arrows filling the space like in the example plot above).

**Comment by agisga** [comment]
@smilesun It's possible to load the data from the tensorboard "event" files of finished runs and plot these graphs with arrows in matplotlib.
Here is an example for a single run:

![image](https://github.com/marrlab/DomainLab/assets/11449372/e85c1860-1cb3-4896-bf38-8038ccaac0bd)

With multiple runs on the same plot it gets quite chaotic though:

![image](https://github.com/marrlab/DomainLab/assets/11449372/6ce0c21c-5348-4e0d-9e06-f1e4254bcb81)

What do you think?

**Comment by smilesun** [comment]
I think it looks very nice already. Thanks a lot.
