### ISSUE TITLE
initialization of mu vector

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#441]
@ntchen ,  shall we maybe also do a hyper-parameter search for its intilization value of multiplier mu?  maybe it does not make sense to set all mu to be 1?  Maybe you could give some thoughts? 

https://github.com/marrlab/DomainLab/blob/593c34499d96c6c84cfe5b4a809d800260bc5d41/domainlab/algos/trainers/fbopt_alternate.py#L34

To sample that, we need to set those hyper-parameters.

**Comment by ntchen** [comment]
we can try 1- 1000

**Comment by smilesun** [comment]
But mu is a vector, for diva, the hyper parameters from the paper are
rather different scale . Some are 1 some are 1e5

**Comment by ntchen** [comment]
it is quite high. If R is not extremely low, I doubt the performance of other loss terms. but to follow the diva, we can set the initial mu to 1~1e5 and max mu to 1e6.

**Comment by smilesun** [comment]
As discussed, it might be totally ok to set all components of the mu vector to be 1.0, we have to see
