### ISSUE TITLE
bug in calculating task loss

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#444]
https://github.com/marrlab/DomainLab/blob/0420c90c5fd08f99d5543eebb8f4558e00c36968/domainlab/models/model_vae_xyd_classif.py#L34

**Comment by smilesun** [comment]
https://github.com/marrlab/DomainLab/pull/445

**Comment by e-dorigatti** [comment]
I guess this is the underlying reason for #440

**Comment by smilesun** [comment]
I think #440 is another problem, if you look at the pr I made, there is no change for the bug, it just fix the math . The problem for #440 is for some reason self.gamma is None. Which can be that they are not registered

**Comment by smilesun** [comment]
We could fix gammay in the benchmark @e-dorigatti so that it is not none

**Comment by smilesun** [comment]
Like this 


gamma_y:
    min: 1e4
    max: 1e6
    step: 100
    distribution: loguniform
