### ISSUE TITLE
change model name by appending model name suffix of slurm job id if model is run on slurm

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#456]

**Comment by e-dorigatti** [comment]
does this not work? #434

**Comment by smilesun** [comment]
I mean put a line into master branch, since if we won't manage to fix the unit test in fbopt, we have to rely on master to generate benchmark for the baseline methods, does that make sense?

**Comment by smilesun** [comment]
in this PR   https://github.com/marrlab/DomainLab/pull/468
