### ISSUE TITLE
Compare if dann regularization loss is not sign inverted and inversted, how the fbopt behave using tensorboard

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#471]
the domain classification loss should be maximized for dann, but fbopt only move regularizaton smaller, inverting the sign seems the solution, but experiments need to be done using tensorboard to see the behavior.

https://github.com/marrlab/DomainLab/pull/470

**Comment by ntchen** [comment]
Yes, inverting the sign should be the solution
