### ISSUE TITLE
benchmark jigen on PACS

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#519]
We have new version of code, when the old benchmark is done 

```
git clone https://github.com/marrlab/DomainLab.git domainlab_jigen
cd domainlab_jigen
git checkout fbopt
./run_benchmark_slurm examples/benchmark/pacs_jigen_fbopt_alone.yaml 10
```

@drEast ; please use the latest code, could you write a message when this is running?

**Comment by e-dorigatti** [comment]
running with seed 8935

**Comment by smilesun** [comment]
> running with seed 8935

you have  a version with different random seeds already, this issue is not priority.

**Comment by e-dorigatti** [comment]
ah ok, then I stopped this run and started #539
