### ISSUE TITLE
run baselines for diva

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#523]
```
git checkout fbopt
git pull
./run_benchmark_slurm.sh examples/benchmark/pacs_diva_fbopt_and_others.yaml 10
```

**Comment by DanScarc** [comment]
I could also commit the change in `examples/benchmark/pacs_diva_others.yaml` if you want.

**Comment by smilesun** [comment]
you have to make a pull request to change branch fbopt,  welcome, of
course, I have just updated the fbopt branch, could you update?


best,
Xudong
https://smilesun.github.io/

**Comment by smilesun** [comment]
@DanScarc , don't forget to 

git checkout fbopt
git pull  # i have updated a lot of codes
rm -r zoutput
rm -r runs
rm .snakemake

**Comment by DanScarc** [comment]
When exactly did you push the last updates? I submitted the jobs ~3hrs ago.

**Comment by smilesun** [comment]
could you post the commit.txt file in zoutput folder of your submission?

**Comment by DanScarc** [comment]
Sorry, I am not sure I understand what I am supposed to post. What should be in `commit.txt`? Am I supposed to upload inside and send it together with zoutput folder when results are done?

**Comment by smilesun** [comment]
in the zouput folder, there should be a text file called commit.txt, did you find it?  you can open the file and let me know the text inside, just post the text message in commit.txt here?

**Comment by DanScarc** [comment]
```
use git log |grep
consider remove leading b in the line below
b771b0c8b
```

**Comment by smilesun** [comment]
commit 771b0c8be7ba8a57bfd1fbc5106d3fcdab702954 (HEAD -> fbopt, origin/fbopt)
Author: Xudong Sun <smilesun@users.noreply.github.com>
Date:   Sat Oct 14 00:13:05 2023 +0200

    Create pacs_jigen_baslines4fbopt.yaml


that commit is not 3 hours ago when you wrote the message 8 hour ago.

**Comment by DanScarc** [comment]
Okay then should I rerun everything again if the new commit is relevant to my task?

**Comment by smilesun** [comment]
it looks like your code is the latest already

**Comment by DanScarc** [comment]
How did you assess that?

**Comment by smilesun** [comment]
> When exactly did you push the last updates? I submitted the jobs ~3hrs ago successfully. CUDA errors have disappeared after the installation update in #540.

this message you sent at around 00:20 today so 3 hours ago means 21:20 on Friday.

inside a github repository, you could search a specific commit via
`git show 771b0c8b`



from the following file you sent upstairs:
```

use git log |grep
consider remove leading b in the line below
b771b0c8b
```
where I have removed the first "b" in the git commit hash. 


This file is generated everytime you submit a benchmark, it is generated inside the zoutput folder when you submitted your job on the cluster.

**Comment by smilesun** [comment]
git show command let you know the time of commit, and also commit message, you can search also here

https://github.com/marrlab/DomainLab/pull/462

**Comment by smilesun** [comment]
> When exactly did you push the last updates? I submitted the jobs ~3hrs ago successfully. CUDA errors have disappeared after the installation update in #540.

so you did a resubmition at 00:20 on saturday before which you killed the jobs you submitted "3 hours ago"?

**Comment by DanScarc** [comment]
No, I submitted the jobs at around 9pm on Friday. Did not resubmit anything after that. 
That was it.

**Comment by DanScarc** [comment]
That's why I am saying maybe it's better to resubmit everything to be sure. But you decide.

**Comment by smilesun** [comment]
> ```
> use git log |grep
> consider remove leading b in the line below
> b771b0c8b
> ```

if you submitted 21:00 on Friday it is not possible to have this commit message since this commit message only exsit after Saturday 00:13, did you run "git update" in between in the repository?  even that is not possible, since the commit.txt should be generated when the submission started and not possible to be changed anymore even when you re-submit

**Comment by smilesun** [comment]
we have to know how did you get this commit.txt file

**Comment by smilesun** [comment]
you could also post the results of

`git status`
and 
`git log `

here in your **cluster folde where the job is submitted  at 21:00 Friday** , you could make screen shot as well and paste the image here.

**Comment by DanScarc** [comment]
When I type `git show 771b0c8b` on `fbopt`, I get:

<img width="1099" alt="Screenshot 2023-10-14 at 09 45 48" src="https://github.com/marrlab/DomainLab/assets/84813873/d34fefce-c8f0-436c-aad1-f973a598cdea">

whose author is you, not me. So this commit does not map to something I submitted.

**Comment by DanScarc** [comment]
Today, before branching off `fbopt` to `fbopt-readme-typo`, I pulled the changes from `fbopt`. Could it be that I also pulled your last commit's `commit.txt` that went into mine `zoutput` folder?

**Comment by smilesun** [comment]
You pulled the lastest, that is why git log shows the lastest message. 
but 
zoutput/benchmarks/xxx/commit.txt is not synced at all from github,  since the folder zoput is not synced at all. 

the commit.txt message can not be created out of magic

**Comment by smilesun** [comment]
could you send a screen shot of 
when you cd into the DomainLab folder on the cluster, 
type

cat zoutput/benchmarks/xxx/commit.txt
?

**Comment by smilesun** [comment]
could you also do 

cat zoutput/benchmarks/xx/rule_resulsts/*.csv  and send the screen shot?

**Comment by smilesun** [comment]
could you do 

ls -la commit.txt  ? 

let us see when that commit.txt is generated

**Comment by DanScarc** [comment]
`cat [...]`

<img width="1364" alt="Screenshot 2023-10-14 at 09 58 03" src="https://github.com/marrlab/DomainLab/assets/84813873/ce0371a6-717b-4c48-a062-e07c42e04ee0">

`cat zoutput/benchmarks/xx/rule_resulsts/*.csv`

<img width="1385" alt="Screenshot 2023-10-14 at 10 01 48" src="https://github.com/marrlab/DomainLab/assets/84813873/6c41878a-3ab4-4e0e-8f9b-184f31d8d201">
<img width="1377" alt="Screenshot 2023-10-14 at 10 02 23" src="https://github.com/marrlab/DomainLab/assets/84813873/049c05e5-6d37-4d0b-93dc-534f38349880">
<img width="1426" alt="Screenshot 2023-10-14 at 10 03 09" src="https://github.com/marrlab/DomainLab/assets/84813873/b01be5a7-8ae4-446a-926b-069d751213f3">

`ls -la commit.txt `

<img width="1236" alt="Screenshot 2023-10-14 at 10 05 26" src="https://github.com/marrlab/DomainLab/assets/84813873/7ad6e57d-472b-4059-8e72-9b00dd479394">

**Comment by DanScarc** [comment]
I understand `zoutput/` is not synced but 09:06 is exactly when I pulled.

**Comment by smilesun** [comment]
the only possibility for commit.txt to be modifed on 9:06 is the cluster jobs has waited from 21:00 last night until 9:00 this morning to be executed, but that is not possible since so many jobs have been finished already. 

In any sense, we need at partly of these results so just keep them running and let us see. 


Could you do 

cat zoutput/bencmarks/pacs_diva_fbopt_and_others/rule_results/*.csv > rst.txt

and send me the txt file

**Comment by smilesun** [comment]
if not possible, you do not have to send, then

ls -la rule_results

the time stamp for some csv file should be between 21:00 yesterday and 9:00 today.

**Comment by DanScarc** [comment]
`ls -la rule_results`

<img width="679" alt="Screenshot 2023-10-14 at 10 28 08" src="https://github.com/marrlab/DomainLab/assets/84813873/ab4170e0-52e1-4154-aac6-be8cec8459d8">

**Comment by DanScarc** [comment]
`cat zoutput/bencmarks/pacs_diva_fbopt_and_others/rule_results/*.csv > rst.txt
`
<img width="1370" alt="Screenshot 2023-10-14 at 10 30 21" src="https://github.com/marrlab/DomainLab/assets/84813873/5aafac3d-9cb9-49e5-a255-59cf82f47a01">

**Comment by DanScarc** [comment]
How did you find the results, by the way?

**Comment by DanScarc** [comment]
[rst.txt](https://github.com/marrlab/DomainLab/files/12903855/rst.txt)

There you go.

**Comment by smilesun** [comment]
> How did you find the results, by the way?

parts of the results will be used

**Comment by smilesun** [comment]
could you do this one? 

https://github.com/marrlab/DomainLab/issues/546
