### ISSUE TITLE
benchmark diva alone 

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#546]
Could you kill all running jobs and do this now ? 
```
git clone https://github.com/marrlab/DomainLab.git   domainlab_diva
cd domainlab_diva
git checkout fbopt
./run_benchmark_slurm.sh examples/benchmark/pacs_diva_fbopt_alone.yaml
```

**Comment by smilesun** [comment]
please use commits later than this one:

https://github.com/marrlab/DomainLab/pull/462/commits/ec8db316dfaf694674cd719f223d27e4d6addf23

**Comment by DanScarc** [comment]
<img width="1424" alt="Screenshot 2023-10-14 at 12 59 31" src="https://github.com/marrlab/DomainLab/assets/84813873/9732888e-7c41-4ac8-ae5f-ce46b36d8b08">

**Comment by DanScarc** [comment]
Is that expected?
I followed you instructions precisely.

**Comment by smilesun** [comment]
could you "cat" one of the err files showed in your screen shot?

**Comment by DanScarc** [comment]
Sorry, I think forgot to copy pacs in the new directory.

<img width="1195" alt="Screenshot 2023-10-14 at 13 21 13" src="https://github.com/marrlab/DomainLab/assets/84813873/90171215-0408-478a-95ff-a9840d3170af">

**Comment by smilesun** [comment]
ok, fine, dont run anything now

**Comment by smilesun** [comment]
i will assign a new task to you

**Comment by smilesun** [comment]
also you dont need to "copy", just create a symbolic link is enough using sh_pacs.sh

**Comment by DanScarc** [comment]
I can proceed with this task by fixing the error if you want.

**Comment by smilesun** [comment]
no, please do this one
https://github.com/marrlab/DomainLab/issues/547

I will fix a problem before you come back to the current issue, i will close it now
