### ISSUE TITLE
benchmark diva baselines

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#547]
```
git clone https://github.com/marrlab/DomainLab.git   domainlab_diva
cd domainlab_diva
git checkout fbopt
./run_benchmark_slurm.sh examples/benchmark/pacs_diva_others.yaml
```

you can use the same folder if you want, make sure to clean up everything, a short cut is 

`git clean -df `

Let me know when this is running.

**Comment by DanScarc** [comment]
Running error-free since 5' ago.

**Comment by DanScarc** [comment]
I attach the results for you here.

[rst.txt](https://github.com/marrlab/DomainLab/files/12910675/rst.txt)
