### ISSUE TITLE
benchmark diva alone

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#553]
```
git clone https://github.com/marrlab/DomainLab.git   domainlab_diva
cd domainlab_diva
git checkout fbopt
./run_benchmark_slurm examples/benchmark/pacs_diva_fbopt_alone_es5.yaml 10
```

**Comment by DanScarc** [comment]
Running successfully.

**Comment by DanScarc** [comment]
[rst.txt](https://github.com/marrlab/DomainLab/files/12914080/rst.txt)

**Comment by DanScarc** [comment]
Results before [bug](https://github.com/marrlab/DomainLab/pull/462/commits/343d4ab9a80b7e3e5a68df373aae47a00d52a7fd) in yaml:
[rst_bug.txt](https://github.com/marrlab/DomainLab/files/12921188/rst_bug.txt)

**Comment by smilesun** [comment]
'str_diva_multiplier_type': 'gammad_recon'

we probably should not run this option at all.

**Comment by DanScarc** [comment]
Should we be concerned about this? This has never happened so far to my knowledge.
<img width="1363" alt="Screenshot 2023-10-16 at 22 14 59" src="https://github.com/marrlab/DomainLab/assets/84813873/81176efb-035e-4a7a-8b16-6413c8385ab3">

**Comment by smilesun** [comment]
could you `vim` one of them and send a screen shot where the error message occur?

**Comment by DanScarc** [comment]
[error_log.txt](https://github.com/marrlab/DomainLab/files/12921536/error_log.txt)

**Comment by smilesun** [comment]
tks, it is my prlbem, i printed the name "error",  will change the code so that "error" would not occur in loggin

**Comment by smilesun** [comment]
so code is fine

**Comment by smilesun** [comment]
@DanScarc , fixed in latest commit

https://github.com/marrlab/DomainLab/pull/462/commits/1d6345be904f3eed2b3d0afa4a2d1d8c56beba00

**Comment by DanScarc** [comment]
Should I rerun again, then?

**Comment by smilesun** [comment]
no

**Comment by smilesun** [comment]
post some results tomorrow morning here

**Comment by DanScarc** [comment]
Perfect, as suspected. I'll post results tomorrow!

**Comment by DanScarc** [comment]
[rst.txt](https://github.com/marrlab/DomainLab/files/12926004/rst.txt)
Here you go.

**Comment by smilesun** [comment]
so most jobs get stopped at iteration 8, i will fix this issue so we could run them long enough
https://github.com/marrlab/DomainLab/issues/572

**Comment by smilesun** [comment]
fixed, could you **pull** and rerun the same yaml file? 

you could delete all historical folders already.

**Comment by smilesun** [comment]
wait, let me do a last edit to yaml file

**Comment by DanScarc** [comment]
Running since 10'.

**Comment by DanScarc** [comment]
Ah ok, then killing jobs now. You tell me when you're sure.

**Comment by smilesun** [comment]
done, please run now

**Comment by smilesun** [comment]
snake make should use 3 cores at the moment.

**Comment by smilesun** [comment]
https://github.com/marrlab/DomainLab/pull/462/commits/4007dc8b52005d9773265d216d2bd27443373147,

use  at least this commit

**Comment by smilesun** [comment]
do we have some intermediate results?

**Comment by DanScarc** [comment]
Yes.
[rst.txt](https://github.com/marrlab/DomainLab/files/12995112/rst.txt)

**Comment by DanScarc** [comment]
Updated results below
[rst.txt](https://github.com/marrlab/DomainLab/files/13030504/rst.txt)
