### ISSUE TITLE
post results.csv file for benchmarking jigen here

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#555]

**Comment by drEast** [comment]
sent on slack

**Comment by smilesun** [comment]
[rst.csv](https://github.com/marrlab/DomainLab/files/12920006/rst.csv)

**Comment by smilesun** [comment]
[pacs_jigen_felix_baselines.csv](https://github.com/marrlab/DomainLab/files/12937832/pacs_jigen_felix_baselines.csv)
