### ISSUE TITLE
log the epoch number when the model is selected

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#558]

**Comment by MatteoWohlrapp** [comment]
Are we not logging the epoch already in the Exp object and again in the Observer?

**Comment by smilesun** [comment]
> Are we not logging the epoch already in the Exp object and again in the Observer?

We do, but do not know when the model is selected, which epoch it is, right?  By the end of training, we save results including commit hash, model used, method name, performance metric (acc, F1, etc) and how many epochs are executed,   but we do not know the epoch number when the model is selected, right?
