### ISSUE TITLE
clean up yaml file for diva_fbopt and its baselines

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#578]
currently we have separate yaml files for baselines of fbopt and fbopt alone so that we could find some good configurations first for fbopt alone and then combine them with the baselines to re-do the benchmark to ensure reproducibility:  
we need to edit this file by changing the configurations of fbopt according to our tuning process and also ensure the whole benchmark can be finished within a few days (i.e. not too many lines in hyperparameters.csv and not too many random seeds but also not too less) 

https://github.com/marrlab/DomainLab/blob/fbopt/examples/benchmark/pacs_diva_fbopt_and_others.yaml

**Comment by smilesun** [comment]
some partial results?

**Comment by DanScarc** [comment]
[rst.csv](https://github.com/marrlab/DomainLab/files/13068447/rst.csv)

**Comment by smilesun** [comment]
is the benchmark completely done?

**Comment by DanScarc** [comment]
I'll send in a moment!

**Comment by DanScarc** [comment]
[rst.csv](https://github.com/marrlab/DomainLab/files/13117698/rst.csv)

**Comment by smilesun** [comment]
commit 46fd90b1f10acc7662164419b431d44c99c7b9ba

**Comment by DanScarc** [comment]
Shall we run this?

**Comment by smilesun** [comment]
could you run 

examples/benchmark/pacs_diva_fbopt_alone_es1.yaml with **starting seed 3** ?

**Comment by DanScarc** [comment]
Sure, on it.

**Comment by smilesun** [comment]
could you send the plots according to instructions here:

https://github.com/marrlab/DomainLab/blob/master/docs/doc_benchmark.md#output-folder-structure,

we need the plot

**Comment by DanScarc** [comment]
I'll do as soon as it's done

**Comment by smilesun** [comment]
for next time plots, we just use this one:

`graphics/variational_plot/acc/stochastic_variation.png`
