### ISSUE TITLE
analyze effect of mu cap and exponential shoulder cap

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#580]
please post results here, intermediate or final 
https://github.com/marrlab/DomainLab/blob/fbopt/examples/benchmark/pacs_diva_fbopt_alone_es1_daniele.yaml
Consider make es=1 to a higher value if results not good enough

**Comment by DanScarc** [comment]
I don't think results are that much better. Here they are

[rst.txt](https://github.com/marrlab/DomainLab/files/13043309/rst.txt)
[rst.csv](https://github.com/marrlab/DomainLab/files/13043311/rst.csv)

**Comment by smilesun** [comment]
```
13, diva_fbopt_full, diva, 25, sketch, 10, "{'str_diva_multiplier_type': 'gammad_recon_per_pixel', 'mu_clip': 10, 'exp_shoulder_clip': 5}", 0.69152457, 0.72758245, 0.70445216, 0.94630516, 0.6867132, 0.9193133, 0.69712394, 0.9995051, 0.66709083
13, diva_fbopt_full, diva, 29, sketch, 11, "{'str_diva_multiplier_type': 'gammad_recon_per_pixel', 'mu_clip': 10, 'exp_shoulder_clip': 5}", 0.72003055, 0.80517805, 0.7458248, 0.950449, 0.74299854, 0.93922687, 0.7378468, 0.9996701, 0.0
13, diva_fbopt_full, diva, 25, sketch, 12, "{'str_diva_multiplier_type': 'gammad_recon_per_pixel', 'mu_clip': 10, 'exp_shoulder_clip': 5}", 0.7085773, 0.7521316, 0.71482074, 0.949061, 0.7133055, 0.91733485, 0.7195215, 0.99851537, 0.6719267

0, diva_fbopt_full, diva, 23, sketch, 10, "{'str_diva_multiplier_type': 'gammad_recon', 'mu_clip': 10, 'exp_shoulder_clip': 2}", 0.6935607, 0.7624309, 0.7276481, 0.9468061, 0.69710326, 0.927437, 0.7151947, 0.999835, 0.6602189
0, diva_fbopt_full, diva, 22, sketch, 11, "{'str_diva_multiplier_type': 'gammad_recon', 'mu_clip': 10, 'exp_shoulder_clip': 2}", 0.7355561, 0.78241754, 0.76743627, 0.9537545, 0.7496357, 0.93039787, 0.74319166, 0.9996701, 0.0
0, diva_fbopt_full, diva, 21, sketch, 12, "{'str_diva_multiplier_type': 'gammad_recon', 'mu_clip': 10, 'exp_shoulder_clip': 2}", 0.7149402, 0.7754512, 0.7479012, 0.9506205, 0.7241764, 0.93492943, 0.7452278, 1.0, 0.72283024
```

**Comment by smilesun** [comment]
any update?

**Comment by DanScarc** [comment]
Yes, sorry, had 0 time to look at it.
[rst.csv](https://github.com/marrlab/DomainLab/files/13055000/rst.csv)

**Comment by DanScarc** [comment]
Seems to have reproduced but with more epochs.

**Comment by smilesun** [comment]
which yaml file did you use? could you post it somewhere or make a pr?

**Comment by DanScarc** [comment]
it's on branch `fbopt-reproducibility` under `examples/benchmark/pacs_diva_fbopt_alone_es1_reprod.yaml`.

**Comment by smilesun** [comment]
what is the major difference that has brough the improvements?

**Comment by DanScarc** [comment]
I slightly noticed that `mu_init` is generally lower for better results, i.e. 1e-06 but it also interacts quite heavily with `k_i_gain`, correct?

**Comment by smilesun** [comment]
I think mu_exponential_shoulder_cap is playing a bigger rule, this value can not be bigger than 5.

**Comment by smilesun** [comment]
while mu_init and k_i_gain is not ? @DanScarc
