### ISSUE TITLE
write a script to plot all curves in tensorboard diva

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#582]
The tensorboard can be reproduced by  `bash run_fbopt_mnist_diva.sh`

A better plot can be done via 
`python domainlab/utils/generate_fbopt_phase_portrait.py --str2="lossrd/dyn_gamma_d" --str1="lossrs/setpoint_gamma_d"`

(a file called timecourse.png will be generated see below)

But this is too slow when we want to plot everything, so it make sense by looking at the code https://github.com/marrlab/DomainLab/blob/27915b37d0aba646a908de0cf0305eb9409b7ce2/domainlab/algos/trainers/fbopt_mu_controller.py#L172

and make a rule for the naming and put them in a configuration file and we can get a script to convert all tensorboard plot to matplotlib plot with high resolution. 

![image](https://github.com/marrlab/DomainLab/assets/570694/ff8685df-f29b-49c0-8d08-47b3ffe5be67)

![timecourse](https://github.com/marrlab/DomainLab/assets/570694/61c21d07-cb87-4b47-96cf-0f11b1878705)

**Comment by agisga** [comment]
> But this is too slow when we want to plot everything,

In which way is it slow? You mean it takes long for the script to execute, or you mean the human effort to input the command line?

> and make a rule for the naming and put them in a configuration file

Do you mean that, `list_str_multiplier_na[i]` should be standardized somehow in statements such as `self.writer.add_scalar( f'lossrd/dyn_{list_str_multiplier_na[i]}', reg_dyn, miter)`?

**Comment by smilesun** [comment]
> > But this is too slow when we want to plot everything,
> 
> In which way is it slow? You mean it takes long for the script to execute, or you mean the human effort to input the command line?
> 
too slow: To plot everything in tensorboard we have to call `python domainlab/utils/generate_fbopt_phase_portrait.py --str2=[name1]" --str1="[name2]"`, there are too many combinations for tensorboard for diva fbopt. To make it "faster", we could either write a bash script by writing many lines of `python domainlab/utils/generate_fbopt_phase_portrait.py --str2=[name1]" --str1="[name2]"` to include all combinations of each loss function and their setpoint so that each time we call `bash run_fbopt_mnist_diva.sh` we can call a bash script like `bash generate_all_figures.sh` to plot every loss time course.
With this script, we just run it and we will have all png files in the current directory to choose from to put into the paper. 
  Does that make sense? 
> > and make a rule for the naming and put them in a configuration file
> 
> Do you mean that, `list_str_multiplier_na[i]` should be standardized somehow in statements such as `self.writer.add_scalar( f'lossrd/dyn_{list_str_multiplier_na[i]}', reg_dyn, miter)`?
this line ensures the key matches https://github.com/marrlab/DomainLab/blob/5a67544dba15a24b9584a9725f079da031d45bb3/domainlab/algos/trainers/fbopt_mu_controller.py#L168C13-L168C16
here, I have used https://github.com/marrlab/DomainLab/blob/5a67544dba15a24b9584a9725f079da031d45bb3/domainlab/utils/generate_fbopt_phase_portrait.py#L76
to plot the legend, but if we use  the legend here to put into the paper, it might look a bit strange, so maybe we need to change the names of `self.writer.add_scalar( f'lossrd/dyn_{list_str_multiplier_na[i]}', reg_dyn, miter)`? into  something more readable `self.writer.add_scalar( f'loss_dynamic_corresponding_to_multiplier_{list_str_multiplier_na[i]}', reg_dyn, miter)`?

**Comment by agisga** [comment]
>  so maybe we need to change the names of self.writer.add_scalar( f'lossrd/dyn_{list_str_multiplier_na[i]}', reg_dyn, miter)? into something more readable self.writer.add_scalar( f'loss_dynamic_corresponding_to_multiplier_{list_str_multiplier_na[i]}', reg_dyn, miter)

Okay, I can make this change. And then I'll make a script like `generate_all_figures.sh`, except it would be specific to diva, right? (so, `generate_all_figures_diva.sh`)

**Comment by smilesun** [comment]
> > so maybe we need to change the names of self.writer.add_scalar( f'lossrd/dyn_{list_str_multiplier_na[i]}', reg_dyn, miter)? into something more readable self.writer.add_scalar( f'loss_dynamic_corresponding_to_multiplier_{list_str_multiplier_na[i]}', reg_dyn, miter)
> 
> Okay, I can make this change. And then I'll make a script like `generate_all_figures.sh`, except it would be specific to diva, right? (so, `generate_all_figures_diva.sh`)

yes. It should contain each component of R loss and the setpoint, this can already be generated via something like
`python domainlab/utils/generate_fbopt_phase_portrait.py --str2="lossrd/dyn_gamma_d" --str1="lossrs/setpoint_gamma_d"`

**Comment by agisga** [comment]
@smilesun See the script to generate all figures here: <https://github.com/marrlab/DomainLab/blob/fbopt/generate_all_figures_diva.sh>
For the curve labels, I introduced additional command line arguments that are set in the .sh script. I thought that will give us more flexibility if the labels need to be adjusted for the paper. Hope that's okay.
Please let me know if I should make any adjustments.
