### ISSUE TITLE
benchmark pacs data for jigen and baselines

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#586]
step 1:
use  https://github.com/marrlab/DomainLab/blob/fbopt/examples/benchmark/pacs_jigen_fbopt_and_others.yaml
`bash run_benchmark_slurm examples/benchmark/pacs_jigen_fbopt_and_others.yaml [start_seed]`

Could you please post the start seed here and post intermediate results  in between so we know if we need to run jigen with fbopt alone to find the good configuration? 

step 2:
If any jobs failed, use 

https://github.com/marrlab/DomainLab/blob/master/docs/doc_benchmark.md#obtain-partial-results

or 

https://github.com/marrlab/DomainLab/blob/master/docs/doc_benchmark.md#generate-plots-from-csv-file

step 3:

upload the plot in zoutput/benchmarks/[name-of-the-benchmark]/graphics/variational_plots/acc/stochastic_variation.png to overleaf and write captions to explain the results. 

step 4:
if fbopt has not got a large win margin compared to baselines, update 
https://github.com/marrlab/DomainLab/blob/fbopt/examples/benchmark/pacs_jigen_fbopt_alone.yaml
and find good configurations and merge results with baselines.

**Comment by drEast** [comment]
Started seed 0

**Comment by smilesun** [comment]
any intermediate results so that we know if we need to run a separate yaml file for fbopt alone?

**Comment by smilesun** [comment]
@drEast ? any update will be useful so we know if we need to launch another experiment

**Comment by smilesun** [comment]
@drEast i will split each step in different issues for you to run and close the current one
