### ISSUE TITLE
benchmark jigen alone with force_setpoint_change_once

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#609]
https://github.com/marrlab/DomainLab/blob/fbopt/examples/benchmark/pacs_jigen_fbopt_alone_autoki.yaml

`bash submit_slurm_via_cpu_10days.sh examples/benchmark/pacs_jigen_fbopt_alone_autoki.yaml 0`

**Comment by DanScarc** [comment]
Running now 👍🏼

**Comment by smilesun** [comment]
any intermediate results?

**Comment by DanScarc** [comment]
Not yet :(

**Comment by smilesun** [comment]
it looks like https://github.com/marrlab/DomainLab/issues/625 should not be a bug, but let us check later to see if there are other errors like this. 

Could you paste  the output of `bash sh_list_errors.sh zoutput/slurm_logs` here?

**Comment by DanScarc** [comment]
[slurm_logs.txt](https://github.com/marrlab/DomainLab/files/13242097/slurm_logs.txt)
