### ISSUE TITLE
study the effect of exp_shoulder_clip on out of distribution performance

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#617]
use tensorboard to study when exp_shoulder_clip is big and small and their contribution to the results on sketch domain performance in PACS

https://github.com/marrlab/DomainLab/blob/b085b29d9d79fa0c0b5b871d726b78bea38511e7/domainlab/algos/trainers/args_fbopt.py#L37

**Comment by agisga** [comment]
https://github.com/marrlab/DomainLab/blob/fbopt/examples/benchmark/pacs_diva_fbopt_alone_es1_autoki.yaml

Similar to this file, make a new one to study the behaviour of ki and shoulder clip

**Comment by smilesun** [comment]
if you want to use slurm, you have to change this file to fit your need https://github.com/marrlab/DomainLab/blob/master/examples/yaml/slurm/config.yaml

**Comment by agisga** [comment]
From initial benchmark results it appears that the performance is poor when large k_i_gain_ratio (about 16) is combined with a large exp_shoulder_clip.

**Comment by smilesun** [comment]
I agree that means we don’t have to use large gain
