### ISSUE TITLE
benchmark hduva with fbopt

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#637]
https://github.com/marrlab/DomainLab/blob/fbopt/examples/benchmark/pacs_hduva_fbopt_alone_es1_autoki_aug.yaml

`bash submit_slurm_via_cpu_3days.sh examples/benchmark/pacs_hduva_fbopt_alone_es1_autoki_aug.yaml 0
`

**Comment by DanScarc** [comment]
Running now

**Comment by smilesun** [comment]
any intermediate results?

**Comment by DanScarc** [comment]
[run_experiment-index=0-14231791.txt](https://github.com/marrlab/DomainLab/files/13389213/run_experiment-index.0-14231791.txt)
[run_experiment-index=0-14197446.txt](https://github.com/marrlab/DomainLab/files/13389214/run_experiment-index.0-14197446.txt)
[run_experiment-index=0-14220318.txt](https://github.com/marrlab/DomainLab/files/13389215/run_experiment-index.0-14220318.txt)

**Comment by smilesun** [comment]
I updated the yaml, could you run them again?

**Comment by smilesun** [comment]
maybe delete the zoutput folder to save some space?
