### ISSUE TITLE
use validation acc above threshold to reset early stop counter

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#677]
with a commandline argument from the parser, the user input a validation acc, training should not stop before this validation acc is reached, i.e. one could reset the early stop counter to avoid early stop in this case.

**Comment by MatteoWohlrapp** [comment]
Are we stopping at the end of the specified number of epochs or are we also overwriting that with the argument?

**Comment by smilesun** [comment]
> Are we stopping at the end of the specified number of epochs or are we also overwriting that with the argument?

- The args.epos specifies the maximum number of epochs to run, i.e.  the computation budget
- counter for early stop is to cease training before this maximum number of epochs reached. 
- if we enable this val-acc feature, then the early stop counter will remain zero before val-acc reaches a specified value, so the training will continue until args.epos (i.e. maximum number of epochs or computation budget) reached. 

Is the software behavior specification clear now?

**Comment by smilesun** [comment]
One quick solution can be 
- use mnist-color (only use two training domains and test on only one domain) or vlcs-mini, see `python main_out.py --te_d 0  --tr_d 3 7 --task=mnistcolor10`
- use an acc value bigger than 1, e.g. 1.1 
- then set the args.epos to be a big number N
- first, option out this feature, then early stop should let the model stop training maybe after 10 epochs
- then, option this feature, then early stop will never work so training will run until N

Is this a idea worth trial?

**Comment by smilesun** [comment]
See more examples in https://marrlab.github.io/DomainLab/build/html/doc_examples.html to compose your yaml file
