### ISSUE TITLE
gamma_reg name collision when combining models and trainers

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#716]
When we specify model-model, trainer-trainer, model-training combination, e.g. https://github.com/marrlab/DomainLab/blob/master/examples/conf/vlcs_diva_mldg_dial.yaml

It can be there are name collisions of the multiplier $\mu$:

-
https://github.com/marrlab/DomainLab/blob/43d1cda636ba59ed9f2237836aeabf4e0eeb25f0/domainlab/algos/trainers/train_matchdg.py#L39
-https://github.com/marrlab/DomainLab/blob/6126ddeb2df0fe3a07de458cac68e4ad02da3c66/domainlab/algos/trainers/train_mldg.py#L111C19-L111C39

-https://github.com/marrlab/DomainLab/blob/6126ddeb2df0fe3a07de458cac68e4ad02da3c66/domainlab/algos/trainers/train_dial.py#L52

In this case, when i set commandline argument gamma_reg=1.0, it simultaneously set both $\mu$ for MLDG and DIAL to be 1.0.  We need different mechanisms to set different values for the two Trainers. 

# Further importance of this Issue: 

The advantage/one of the major feature for DomainLab is that we can handle training multiple loss terms with multiplier weighting each term,  to circumsvent setting those multipliers mannually,  there are different multiplier schedulers to adapt those multiplier values at each epoch: 

This file is the Trainer which could schedue the values of those multipliers at each epoch,  
https://github.com/marrlab/DomainLab/blob/master/domainlab/algos/trainers/train_hyper_scheduler.py

Inside the Trainer, a hyper_scheduler has to be specified (In the branch fbopt, we define a fully automatic contoller for scheduling the multipliers, in the main branch, the schedulers are 

https://github.com/marrlab/DomainLab/blob/master/domainlab/algos/trainers/hyper_scheduler.py

First, those multipliers (a.k.a. hyperparameters) are initialized
 https://github.com/marrlab/DomainLab/blob/a77dad8a34fc54501e8a3282f53eda1551b7134c/domainlab/algos/trainers/train_hyper_scheduler.py#L28

At each epoch, the multipliers (a.k.a. hyperparameters) are updated via the scheduler
 https://github.com/marrlab/DomainLab/blob/a77dad8a34fc54501e8a3282f53eda1551b7134c/domainlab/algos/trainers/train_hyper_scheduler.py#L63

All $\mu$ need to be registered at the multiplier scheduling

https://github.com/marrlab/DomainLab/blob/43d1cda636ba59ed9f2237836aeabf4e0eeb25f0/domainlab/models/model_diva.py#L112

**Comment by MatteoWohlrapp** [comment]
https://github.com/marrlab/DomainLab/blob/a77dad8a34fc54501e8a3282f53eda1551b7134c/domainlab/models/a_model.py#L94C8-L96C30
