### ISSUE TITLE
compile DomainLab from github CI instead of running API examples directly from pypi website

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#739]
If we have code changes, then the pypi version is always older than the gitub master branch, so having the line in the CI
```
- name: test if api works before setup install since setup install miss data
   run: pip install domainlab && cd examples/api/ && python jigen_dann_transformer.py
```
from https://github.com/marrlab/DomainLab/blob/master/.github/workflows/ci.yml, will not work. 

A better solution is to compile domainlab in github virtual machine and test teh API example, but the following commit does not work

https://github.com/marrlab/DomainLab/commit/afc9697ba3e61dc71bd70901efd37887df9d4011

**Comment by smilesun** [comment]
@agisga ,  latest commit CI was broken due to version inconsistency

https://github.com/marrlab/DomainLab/actions/runs/7594694755/job/20686473459


ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch<2.0.0,>=1.12.0 from https://files.pythonhosted.org/packages/ca/74/7342c7f21449557a8263c925071a55081edd7e9b641404cfe31d6fb71d3b/torch-1.12.1-cp310-cp310-manylinux1_x86_64.whl (from domainlab):
        Expected sha256 9c038662db894a23e49e385df13d47b2a777ffd56d9bcd5b832593fab0a7e286
             Got        5854df658857f4b29a53d79b20496c127471009c89b9cceca6d0b841494f7b90

**Comment by smilesun** [comment]
In the latest commit, I deleted the line
```

    - name: test if api works before setup install since setup install miss data
      run: pip install domainlab && cd examples/api/ && python jigen_dann_transformer.py
```
Is there a way we could add it?

**Comment by smilesun** [comment]
@agisga do you have time to fix this issue this week?

**Comment by agisga** [comment]
Seems like this solves it: https://github.com/marrlab/DomainLab/pull/768 Or am I misunderstanding what the issue is?
