### ISSUE TITLE
fbopt ci failed after merged master into fbopt, with pr commandline interface entry point

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#754]
https://github.com/marrlab/DomainLab/actions/runs/7583966552/job/20656686984#step:7:786
with commit
https://github.com/marrlab/DomainLab/pull/462/commits/aa1d5cd13e6a9db9d829604f81cdc1d7570876cb

no module named tensorboard

the previous commit has no such a problem. 

can it be the pyproject.yaml file?  https://github.com/marrlab/DomainLab/pull/740/files

**Comment by smilesun** [comment]
@agisga , will we get inconsistency now for the requirements.txt which is required by pypi and the pyproject.toml?? 

https://github.com/marrlab/DomainLab/pull/462/commits/2319105e39644757beba7d8aade32ed73576ec8c

**Comment by smilesun** [comment]
now Creating virtualenv domainlab-okngg5wM-py3.10 in /home/runner/.cache/pypoetry/virtualenvs
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Because domainlab depends on tensorboard (^2.14.0) which doesn't match any versions, version solving failed.
Error: Process completed with exit code 1.


https://github.com/marrlab/DomainLab/actions/runs/7584309962/job/20657710847#step:6:132

**Comment by smilesun** [comment]
this commit revert the way how pytest is run

https://github.com/marrlab/DomainLab/pull/462/commits/04a6f25da58c489a1c66cccb6ad2c8885495a4ec

**Comment by agisga** [comment]
> @agisga , will we get inconsistency now for the requirements.txt which is required by pypi and the pyproject.toml??
> 
> [2319105](https://github.com/marrlab/DomainLab/commit/2319105e39644757beba7d8aade32ed73576ec8c)

requirements.txt was generated from pyproject.toml before. Did you rerun https://github.com/marrlab/DomainLab/blob/master/scripts/sh_gen_requirements.sh ?

**Comment by agisga** [comment]
> tensorboard

It's better to run `poetry add tensorboard` instead of editing pyproject.toml by hand. Then it should find a compatible version.
You may also need to run `poetry lock --no-update` if you still get the warning about poetry.lock.

**Comment by smilesun** [comment]
@agisga , do you have time to take a look maybe? I tried several commits but still could not resovle it.

**Comment by agisga** [comment]
> @agisga , do you have time to take a look maybe? I tried several commits but still could not resovle it.

I can take a look at it tomorrow.

**Comment by smilesun** [comment]
thanks! that will be great!

**Comment by agisga** [comment]
> thanks! that will be great!

The PR seems to address the issue, unless I'm misunderstanding something: https://github.com/marrlab/DomainLab/pull/765

**Comment by smilesun** [comment]
> > thanks! that will be great!
> 
> The PR seems to address the issue, unless I'm misunderstanding something: #765

thanks!  How did you find out the version fo tensorboard should be the one you changed to in the pyproject.toml? 

https://github.com/marrlab/DomainLab/pull/462/commits/486d81a1e0c269725d6058faf81e31c474e1fa96

**Comment by agisga** [comment]
> thanks! How did you find out the version fo tensorboard should be the one you changed to in the pyproject.toml?

I first deleted tensorboard from pyproject.toml, and then ran `poetry add tensorboard`. Then poetry determined this specific version to be used. I'm not sure how Poetry decides on what version to use, but I assume that it checks for compatibility with the other packages specified.
