### ISSUE TITLE
rerun the benchmark of fbopt for diva

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#756]
`git clean -df`

`git checkout fbopt`

`git pull`

`./run_benchmark_slurm.sh examples/benchmark/pacs_diva_fbopt_and_baselines.yaml`

**Comment by DanScarc** [comment]
Running

**Comment by smilesun** [comment]
done?

**Comment by smilesun** [comment]
if yes, maybe post it here @DanScarc

**Comment by DanScarc** [comment]
[slurm_errors.txt](https://github.com/marrlab/DomainLab/files/14086228/slurm_errors.txt)

**Comment by smilesun** [comment]
i checked the results, so the error is due to time-out which means we have too many random seeds.

**Comment by DanScarc** [comment]
[temp_results.txt](https://github.com/marrlab/DomainLab/files/14128745/temp_results.txt)
