### ISSUE TITLE
clean up dependencies for effortless installation of DomainLab

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#794]

**Comment by MatteoWohlrapp** [comment]
Can you please provide a more detailed description of this task? 
What does 'effortless installation' refer to? Both through cloning the repo and using pip, the installation was straightforward and did not lead to any dependency-related issues for me.

**Comment by smilesun** [comment]
If that is the case, we could leave it, I mentioned this issue since you once told me you had difficulties installing it.

**Comment by MatteoWohlrapp** [comment]
Yes, but I think it was more connected to some pip issue. Tried it in a new container and works now
