### ISSUE TITLE
Create plots comparing the performance of different models on one dataset

### ISSUE THREAD

**Issue by Car-la-F** [marrlab/DomainLab#80]
Like discussed in the meeting (27.01.23) we like to create these plots:

1. stochastic variation: variation of the accuracy in the test domain over different runs (by using the same hyperparam. but different random seeds)
2. systematic variation: variation of the accuracy in the test domain for different hyperparam. combinations 
3. scatterplot comparing two objectives (maybe even a scatterplotmatrix)
4. star plot including all algorithms and having the objectives on the axes

I was thinking about writing a function for each of the plots. The function shall recive a pandas dataframe, create the plot (with rasonable labeling and axis anotations) and save the plot in a predefined folder. Later we can combine all plotting functions in one function to produce all plots using only one function.

**Comment by Car-la-F** [comment]
To agree on a configuration for the pandas dataframe:
I would propose to stick with the format in which the results are saved in zoutput/aggrsts
algo | epos | seed | aggtag | mname | commit | acc | precision | recall | specificity | f1 | auroc

**Comment by smilesun** [comment]
> To agree on a configuration for the pandas dataframe: I would propose to stick with the format in which the results are saved in zoutput/aggrsts algo | epos | seed | aggtag | mname | commit | acc | precision | recall | specificity | f1 | auroc

for the initial version of the code, yes, we can stick to this,  

for an adanced future solution, one need to read the header to know what to plot in case there is one column added to this header for example.

**Comment by Car-la-F** [comment]
> > To agree on a configuration for the pandas dataframe: I would propose to stick with the format in which the results are saved in zoutput/aggrsts algo | epos | seed | aggtag | mname | commit | acc | precision | recall | specificity | f1 | auroc
> 
> for the initial version of the code, yes, we can stick to this,
> 
> for an adanced future solution, one need to read the header to know what to plot in case there is one column added to this header for example.

From my understanding all columns staring from acc to the right (acc | precision | recall | specificity | f1 | auroc) are the objectives while the other columns (algo | epos | seed | aggtag | mname | commit) give additional information about the run. 
to make this functions more general from the beginning on we may use a different dataframe? Maybe:
algo | epos | seed | hyperparam 1 | ... | hyperparam n | objective 1 | ... | objective m

**Comment by Car-la-F** [comment]
I pushed two functions generating plot 3 and 4 onto the branch `carla_BenchmarkPlots`.
The functions can be found in `utilis/generate_benchmark_plots.py` together with a dummy dataset representing some results. One can run the python file to see the plots on the dummy dataset.

@xinyuejohn Feel free to use the dummy dataset for testing. For me this was quite helpful
