### ISSUE TITLE
Error in backpack when running a benchmark with fbopt, fishr, and erm. 

### ISSUE THREAD

**Issue by MatteoWohlrapp** [marrlab/DomainLab#836]
When running the [pacs_fbopt_fishr_erm.yaml](https://github.com/marrlab/DomainLab/blob/erm_hyper_init/examples/benchmark/pacs_fbopt_fishr_erm.yaml) on the [erm_hyper_init branch](https://github.com/marrlab/DomainLab/tree/erm_hyper_init), I get the following error: 
![image](https://github.com/marrlab/DomainLab/assets/67182578/ea68749c-56d8-4563-a356-4c30e6a018e5)

**Comment by smilesun** [comment]
> When running the [pacs_fbopt_fishr_erm.yaml](/examples/benchmarks/pacs_fbopt_fishr_erm.yaml), I get the following error: ![image](https://private-user-images.githubusercontent.com/67182578/330338268-ea68749c-56d8-4563-a356-4c30e6a018e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzM5MzQsIm5iZiI6MTcxNTY3MzYzNCwicGF0aCI6Ii82NzE4MjU3OC8zMzAzMzgyNjgtZWE2ODc0OWMtNTZkOC00NTYzLWEzNTYtNGMzMGU2YTAxOGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA4MDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNDc2YjYxNjQwYTE1MzQ2MjNjNDdkMTllYzE0YmUyZDI0ZmE4NTUwZTE0ZWY3OTRhZWE0YTliNmRiM2ViM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UF2IH2yGGd7mROqaHaPWYL41lpVMK8TVn0yD1LpAeBo)

which branch?

**Comment by MatteoWohlrapp** [comment]
But I get the same error when removing fbopt from the task and only use fishr. So I am not sure if it is connected to fbopt

**Comment by smilesun** [comment]
> But I get the same error when removing fbopt from the task and only use fishr. So I am not sure if it is connected to fbopt

Backpack does not work with skip connections, seems like, see error message here
https://github.com/marrlab/DomainLab/pull/837/files

**Comment by smilesun** [comment]
maybe compare with alex net then? @MatteoWohlrapp

**Comment by smilesun** [comment]
@MatteoWohlrapp , this one seems to be running without error on my acoucnt:

https://github.com/marrlab/DomainLab/pull/838
