### ISSUE TITLE
Create config for testing benchmark

### ISSUE THREAD

**Issue by schoersch** [marrlab/DomainLab#97]
We need a yaml according to [this](https://github.com/marrlab/DomainLab/issues/81#issuecomment-1418230863) which is suitable to test the benchmark. I think it would be fine if we just add a second task with a different algorithm to this yaml.

@xinyuejohn @rahulbshrestha @Car-la-F somebody interested?

**Comment by rahulbshrestha** [comment]
yup, I'll work on it
